(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [
		{name:"index_atlas_", frames: [[0,775,140,77],[0,0,320,480],[0,704,161,69],[219,703,127,120],[219,482,135,219],[0,482,217,220]]}
];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != null && cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != null && cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != null && cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib.interstetititialorangefruite = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.interstitialatasteoftable = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.interstitialcranberries = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.interstitialgreens = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.interstitialmashedpotatoes = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();



(lib.interstitialturkey = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(5);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.whiterectanglefade = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ege2AqlMAAAhVJMA9tAAAMAAABVJg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.whiterectanglefade, new cjs.Rectangle(-197.4,-272.4,395,545), null);


(lib.trynewflavors = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgJBuQgJgDgGgGQgHgGgDgKQgCgKAAgbIAAhiIgRAAIgFgBIgCgFIAAgEQAAgGATgRIAIgGIAHgGQATgRAHAAIAFABQAAABABAAQAAABAAAAQABABAAABQAAAAAAABIAAAjIApAAQAEAAACABQACACAAAFIAAAEQAAAFgCACQgCACgEAAIgmAAIgDACIgBAEIAABaQAAAYAEAFQAEAGALABQAFAAAKgEIAMgDQAEABADACQACADAAADQAAALgPAJQgQAJgTAAQgLAAgJgDg");
	this.shape.setTransform(83.5,102.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgNBfIgUgDIgFADIgGABIgEgBIgDgCQgGgFgGgPQgFgPAAgOQAAgFADgEQADgEAFAAQAIAAAJAPIAHALQAFAHAKAEQAJAFAKAAQANgBAHgFQAHgHAAgKQAAgQgegOIgLgGQgcgOgKgLQgKgLAAgSQAAgXAQgPQARgQAaAAIAMABIANACIAJgDIAGgBQAJAAAIAOQAJAPAAAQQAAAGgDAEQgDADgFAAQgFAAgEgDQgEgEgFgIQgHgMgHgEQgIgFgKAAQgKAAgGAGQgHAGAAAKQAAAIAHAGQAHAHAWALIACABQAzAYAAAfQAAAZgUARQgTARgeAAg");
	this.shape_1.setTransform(68.9,104);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAhBWIgKgJIgIAEQgWAPgWAAQgbAAgRgQQgRgPAAgaQABgdAVgPQAVgRAmAAQAJAAAFADQAFADgBAHQAAAKgMAAQgSAAgLAIQgLAJAAAQQAAAOAJAJQAKAJAQAAQASAAAHgIQAHgIABgTIAAhFQAAgQgIgJQgGgJgNAAQgJAAgHAFQgIADgHAJIgEAEQgLAOgNAAQgGAAgFgEQgFgFABgIQAAgRAVgMQAVgMAhAAQAUAAAOAGQAPAFAJAKQAFAHACAMQADALAAAaIAAA6QAAALABAFQACAFADABIAGABQALAEAAAGQAAAIgMAIQgMAHgQAAQgIAAgJgKg");
	this.shape_2.setTransform(51.6,104);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag7BFQgagbAAgnQAAgqAbgbQAbgdAoAAQAkABAUAUQAVAUAAAiQAAAMgDADQgEADgNABIhGAAQgGAAgDgEQgDgDAAgEQAAgFADgCQADgDAGAAIAmAAIAJgCQACgBAAgEQAAgSgMgMQgMgMgQAAQgWAAgKATQgLATAAAbQAAAcAPAVQAOAUAXAAQANAAAKgCQAJgDAJgGIAGgGQAKgIAFAAQAEAAACAEQADACAAADQAAAFgFAHQgEAGgIAGQgQANgPAGQgOAGgSAAQgmAAgagbg");
	this.shape_3.setTransform(31.9,104);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhcCDQgKgDAAgJQAAgHAJgDQAKgEACgDQACgEACgbIABhHIgBhDQgCgcgCgEQgCgCgKgEQgJgEAAgIQAAgHAIgDQAIgCAgAAIBvAAIASgCIAKgCIAFABIADADQAEAHADAMQADANAAAJQAAAIgDAEQgDAFgFAAQgHAAgHgNIgGgIQgEgGgIgDQgIgDgMAAIgZAAQgRAAgJACQgJACgEAEQgCAEgCAMIgBAjIAAAPQAAAJABACQACACAFAAIAdAAQAPAAAGgEQAFgEACgMIAAgDQADgTAKAAQAIAAADAKQADAJAAAkQAAAigDAKQgDAJgIAAQgKAAgDgTIAAgDQgCgLgFgFQgGgEgPAAIgdAAQgFAAgCADQgBADAAAMIAAAOIABA0QABAKADADIAJAEQALAEAAAIQAAAIgKADQgLADgcAAQgeAAgJgDg");
	this.shape_4.setTransform(11.5,99.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ag3BbQgJgDAAgJQAAgGAJgDIAFgCQAEgDACgGQACgFAAgOIAAgNIAAgOIAAgLQAAgigCgJQgBgLgDgCIgJgDQgLgDAAgHQAAgEAEgDQADgDAHgEIAagIIAQgDQAIABADAYIABADIAAABQAKgOAKgIQAKgIALAAQANAAAHAIQAIAIAAAMQAAANgGAHQgGAIgKgBIgKgBIgHgGIgFgGQgBgGgCAAQgNAAgFASQgEASAAA2QAAAQABAJQACAHAFADIAIACQALADgBAIQABAHgLADQgKADgYAAQgcAAgJgDg");
	this.shape_5.setTransform(-16.5,103.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAnBdQgCgDAAgGIAAgNIAAgBIgBAAQgCAAgEAFIgDACQgJAJgLAFQgJAEgOAAQgOAAgMgFQgMgFgIgKQgJgKgEgPQgDgPAAgmIAAgMIABgOIAAgEQgBgPgCgEQgCgEgGgDIgIgCQgKgDAAgGQAAgFADgDQAEgDANgEIAZgHIAUgDQAFAAACAEQACAEAAAIIAAAHIgCBFQAAAkAIAOQAHAOASAAQAVAAAJgSQAJgSAAgsIAAgOQAAgPgCgEQgCgEgGgDIgIgCQgKgDAAgGQAAgFADgCQAEgEANgEIAZgHIATgDQAFAAADAEQACADAAAJIgBAKIgCBLIABAfIABAMQABAHAJAEIAAAAIAEABQAKAEAAAGQAAAEgDADQgEADgHADIgbAJQgMADgGAAQgGAAgDgDg");
	this.shape_6.setTransform(-35,104);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhCBFQgagbAAgpQAAgoAbgcQAbgcApAAQAnAAAaAaQAZAaAAAoQAAApgbAdQgcAdgnAAQgnAAgagbgAgjg2QgKAPgBAYQAAAkAQAYQAPAZAVAAQASAAALgPQAMgPAAgZQAAgjgPgYQgQgZgVAAQgSAAgMAPg");
	this.shape_7.setTransform(-56,104);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgmCBQgKgDAAgIQAAgIALgEIAIgEQAGgFABhKIAAgRIgWgjIgig3QgLgPgGgEIgJgEQgMgEAAgHQAAgIAJgCQAIgDAkAAQAjAAAJADQAIACAAAIQAAAHgOAFIgBABIgFADIgCAGQAAAEAIANIAkA5IAfgwQAKgRAAgFQAAgFgCgDQgDgDgIgDQgHgDgDgCQgCgDAAgEQAAgIAHgCQAIgDAeAAQAeAAAIADQAHACAAAIQAAAHgKAEIgOAHQgIAHgRAaQgSAagbAuIABAgQABA9AFAEIAIAEQALAEAAAIQAAAIgKADQgKADgdAAQgbAAgLgDg");
	this.shape_8.setTransform(-78.1,100);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ag3BbQgJgDAAgJQAAgFAJgEIAFgBQAEgEACgFQACgHAAgNIAAgNIAAgOIAAgMQAAghgCgJQgBgKgDgDIgJgDQgLgDAAgHQAAgEAEgDQADgEAHgDIAagIIAQgDQAIAAADAZIABADIAAABQAKgOAKgIQAKgIALAAQANAAAHAIQAIAIAAAMQAAANgGAHQgGAIgKgBIgKgBIgHgGIgEgHQgCgEgCAAQgNAAgFARQgEASAAA3QAAAPABAJQACAHAFADIAIACQALADgBAIQABAHgKADQgLADgYAAQgcAAgJgDg");
	this.shape_9.setTransform(81.6,53.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AhCBFQgagbAAgpQAAgpAbgbQAbgcApAAQAnAAAaAaQAZAaAAAoQAAAqgbAcQgcAdgnAAQgnAAgagbgAgig1QgMAOAAAYQAAAkAQAYQAQAZAUAAQATAAAKgPQAMgQAAgYQAAgjgQgYQgPgYgVgBQgSABgLAPg");
	this.shape_10.setTransform(63.9,53.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgzCDQgJgCAAgIQAAgGAJgDIAEgCQAFgCACgGQABgGAAgQIAAgRIAAhYIgUAAQgEAAgCgCQgCgCAAgFIAAgEQAAgFACgCQACgCAEAAIATAAIgBgOIgBgNQAAgcARgQQARgPAdAAQAVAAANAJQANAKAAAOQAAAJgFAEQgFAFgJAAQgFAAgFgDQgFgDgDgEIgDgHQgHgNgLAAQgHAAgDAEQgEAFAAAHIAEAUQADAQABANIAaAAQAFAAABACQACACAAAFIAAAEQAAAFgCACQgCACgEAAIgaAAIAABdQAAAYABAHQACAHADACIAIADQAKADAAAIQAAAHgJADQgJACgZAAQgbAAgJgDg");
	this.shape_11.setTransform(50,49.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgNBfIgUgDIgFADIgGABIgEgBIgDgCQgGgFgGgPQgFgPAAgOQAAgFADgEQADgEAFAAQAIAAAJAOIAHAMQAFAHAKAEQAJAFAKgBQANAAAHgFQAHgHAAgKQAAgQgegOIgLgGQgcgNgKgMQgKgLAAgSQAAgXAQgPQARgQAaAAIAMABIANACIAJgDIAGgBQAJAAAIAOQAJAOAAARQAAAGgDAEQgDADgFAAQgFAAgEgDQgEgDgFgKQgHgLgHgEQgIgFgKAAQgKAAgGAGQgHAGAAAKQAAAIAHAGQAHAHAWALIACABQAzAYAAAeQAAAagUARQgTARgeAAg");
	this.shape_12.setTransform(25.1,53.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("Ag3BbQgJgDAAgJQAAgFAJgEIAFgBQAFgEABgFQADgHAAgNIAAgNIgBgOIAAgMQAAghgCgJQgBgKgDgDIgJgDQgLgDAAgHQAAgEADgDQAEgEAHgDIAZgIIARgDQAJAAACAZIABADIAAABQAKgOALgIQAJgIALAAQAMAAAIAIQAIAIAAAMQAAANgGAHQgGAIgKgBIgJgBIgIgGIgFgHQgBgEgCAAQgNAAgFARQgEASAAA3QAAAPACAJQACAHAEADIAHACQALADAAAIQAAAHgKADQgKADgYAAQgcAAgJgDg");
	this.shape_13.setTransform(10.7,53.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AhCBFQgagbAAgpQAAgpAbgbQAbgcApAAQAnAAAZAaQAaAaAAAoQAAAqgbAcQgbAdgnAAQgoAAgagbgAgig1QgLAOAAAYQAAAkAPAYQAQAZAUAAQATAAALgPQALgQAAgYQAAgjgQgYQgQgYgUgBQgSABgLAPg");
	this.shape_14.setTransform(-7,53.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgTBNQgLgTgZg7IgLgcQgNgigIgEIgFgDQgLgDAAgIQAAgHAJgDQAJgCAeAAQAZAAAJACQAJADAAAHIgBAHIgEACIgGAEQgHADAAADIAEAPIAOAkIAPAjQAEAHACABQACAAAEgGIAIgQIAUgtQAGgSAAgGIgBgGIgEgFIgFgCQgJgDAAgGQAAgHAJgDQAIgCAWAAQAUAAAHACQAIADAAAHQAAAHgJADIgHADQgIAEgQAkIgFALIgHARQgqBegLABQgIgBgKgRg");
	this.shape_15.setTransform(-26.7,53.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAhBWIgKgJIgIAEQgWAPgWAAQgbAAgRgQQgRgPAAgaQAAgdAWgPQAVgRAmAAQAJAAAFADQAEADAAAHQAAAKgMAAQgSAAgLAIQgLAJAAAQQAAAOAJAJQAKAJAQAAQARAAAIgIQAIgIAAgTIAAhFQAAgQgIgJQgHgJgLAAQgKAAgHAFQgIADgHAJIgEAEQgLAOgNAAQgGAAgFgEQgFgFAAgIQABgRAVgMQAVgMAiAAQATAAAPAGQAOAFAIAKQAFAHADAMQACALAAAaIAAA6QAAALACAFQACAFADABIAGABQALAEAAAGQABAIgMAIQgNAHgQAAQgJAAgIgKg");
	this.shape_16.setTransform(-45.8,53.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgeCEQgJgDAAgJQAAgFAIgEIAJgFQADgDABgLIACgkIAAgdIgBgiIAAgNQAAgvgBgNQgCgNgEgCIgLgFQgMgDAAgGQAAgFAEgDQAEgDANgEIAYgHIASgDQAGAAACAEQACADAAAJIAAAOQgCBBAABBIABA/QABANADAEIAKAFQAJADAAAIQAAAGgJAEQgJACgYAAQgbAAgJgCg");
	this.shape_17.setTransform(-61.3,49.3);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AhcCDQgKgDAAgJQAAgHAJgDQAKgEACgDQACgEACgbIABhHIgBhDQgCgcgCgEQgCgCgKgEQgJgEAAgIQAAgHAIgDQAIgCAgAAIBvAAIASgCIAKgCIAFABIADADQAEAHADAMQADANAAAJQAAAIgDAEQgDAFgFAAQgHAAgHgNIgGgIQgEgGgIgDQgIgDgMAAIgZAAQgRAAgJACQgJACgEAEQgCAEgCAMIgBAjIAAAPQAAAJABACQACACAFAAIAdAAQAPAAAGgEQAFgEACgMIAAgDQADgTAKAAQAIAAADAKQADAJAAAkQAAAigDAKQgDAJgIAAQgKAAgDgTIAAgDQgCgLgFgFQgGgEgPAAIgdAAQgFAAgCADQgBADAAAMIAAAOIABA0QABAKADADIAJAEQALAEAAAIQAAAIgKADQgLADgcAAQgeAAgJgDg");
	this.shape_18.setTransform(-76.9,49.3);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AALATIgWg4QgLgZgIgFIgFgDQgLgDAAgIQAAgHAKgDQAIgCAdAAQAZAAAJACQAJADAAAHIgCAGIgDADIgGADQgIAEABADIADANIAPAmIAPAjQAFAHACABQADgBADgFIAJgQIATgtQAHgSAAgGIgCgGIgEgFIgGgCQgHgDgBgGQABgHAHgDQAJgCAXAAQASAAAJACQAHADABAHQAAAHgKADIgGADQgJAEgRAmIgDAJIgIARQgqBfgMAAQgMAAgghMgAhrAKIgFgLIgMgfQgMgfgIgEIgGgDQgLgDABgIQAAgHAJgDQAJgCAeAAQAZAAAJACQAJADAAAHIgBAHIgEACIgGADQgHAEAAADIADAQIAPAjIAPAiQAFAIACABQAFAAAGgMIAFgNIAFgFQACgCAEAAQAEAAADACQACADAAAEQAAAGgEAKQgUAqgIANQgIAPgHAAQgNAAgkhVg");
	this.shape_19.setTransform(57.4,3.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("Ag7BFQgagaAAgoQAAgqAbgcQAbgcAoAAQAkAAAUAVQAVAUAAAiQAAALgDAEQgEAEgNAAIhGAAQgGgBgDgDQgDgDAAgEQAAgFADgCQADgDAGAAIAmAAIAJgCQACgBAAgEQAAgSgMgMQgMgMgQAAQgWAAgKATQgLATAAAbQAAAcAPAVQAOAUAXABQANAAAKgDQAJgEAJgFIAGgGQAKgHAFgBQAEAAACADQADADAAADQAAAFgFAGQgEAHgIAGQgQANgPAGQgOAGgSgBQgmAAgagag");
	this.shape_20.setTransform(32.4,3);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAQAzIgFgIIgogyIglguIgPgSIgBAMIAAAZIAAARQAABQACAUQACAUAGAAQAFAAAFAFQAGAEAAAFQAAAIgJADQgJAEgVAAQgWAAgJgEQgIgDAAgIQAAgHAKgEQAJgEACgCQACgEACgaIABhIIgBhFQgCgbgCgDQgCgDgJgDQgKgEAAgHQAAgIAIgCQAIgEAXAAIAUABIAHADIAaAgIAlAvIAoAyIAdAiIATAVIAAgHIAAgNIgBhbQgBgmgCgFIgCgFIgEgCQgLgEgCgDQgDgCAAgEQAAgIAIgCQAHgEAZAAQAXAAAIAEQAHACAAAIQAAAEgCACIgHAFIgEABQgIADgBAFQgCAHgBAkIgBBuIAAAjIABAWQAAAOgCADQgCAEgFAAQgTAAhChSg");
	this.shape_21.setTransform(8.5,-0.9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AhUB5QgIgIAAgMQAAgIAGgHQAGgGAJAAIAIABIAGAEIAFAGQAEAIAEAAQAJAAAKgOQAJgNAAgPQAAgPgMgdIgCgEIgehAIgQgjQgEgHgKgEIAAgBQgHgCgCgDQgCgCAAgEQAAgJAKgDQAJgCAbAAQAbAAAJACQAJADAAAHIgBAGIgEADIgGADQgIAEABACIADAPIAPAkIAPAjQAEAIADAAQACAAADgIIAMgdIAOglQAFgNgBgEQAAgGgKgGQgKgFAAgFQAAgGAIgDQAJgCAUAAQAXAAAHACQAIADAAAHQAAAHgLADIgHACQgLAGgMAgIgFANIgXA7QgeBLgTAYQgTAWgbAAQgNAAgJgHg");
	this.shape_22.setTransform(-25,6.7);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("Ag3BbQgJgDAAgIQAAgGAJgEIAFgBQAEgDACgGQACgHAAgNIAAgNIAAgOIAAgMQAAgggCgLQgBgJgDgDIgJgDQgLgDAAgHQAAgEAEgDQACgEAIgDIAagIIAQgCQAIgBAEAZIAAADIAAABQAKgOAKgIQAKgIALAAQANAAAHAIQAIAIAAANQAAAMgGAHQgGAIgKAAIgKgCIgHgGIgEgHQgCgEgDAAQgMAAgFARQgEASAAA3QAAAPABAJQADAIAEACIAIACQALAEgBAHQABAHgKADQgLADgYAAQgcAAgJgDg");
	this.shape_23.setTransform(-40.9,2.9);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgmCCQgKgDAAgIQAAgIAKgDQAKgEABgCQACgEACgeIABhWIgBgwIgCgdQAAgGgDgBQgDgBgIAAIgIAAQgMAAgHACQgHAEgGAGIgFAMIgGANIgFAGQgDACgEAAQgFAAgCgFQgDgEAAgMQAAgYAGgPQAFgPAJAAIACABQAPACAWAAIBrAAQAWAAAPgCIACgBQAJAAAFAPQAGAPAAAYQAAALgDAFQgCAFgGAAIgGgCIgGgGIgFgNIgGgMQgFgGgHgEQgHgCgNAAIgHAAQgIAAgDABQgDABgBAGIgBAdIgBAwIABBWQABAeACAEQACACAKAEQAKADAAAIQAAAIgKADQgLADgcAAQgcAAgKgDg");
	this.shape_24.setTransform(-60.2,-1.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.trynewflavors, new cjs.Rectangle(-91.9,-24.9,183.9,148.5), null);


(lib.thanksgiving = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhDB4QgXgPAAgUQAAgJAEgGQAFgGAKAAQAIAAAEAEQAFAFACAIQAEAOAMAHQALAIAXAAQAXAAAQgJQARgKAAgOQAAgIgGgFQgHgFgLAAIgVACIgcABQggAAgSgLQgRgLAAgPQAAgJAGgJQAGgIAOgIQgLgJgFgMQgGgLAAgPQAAgdAXgUQAWgUAjAAIASACIAcAFQAHAAAIgDQAIgEALgIIAGAGIACAGQAAAIgGAHQgFAHgLAGIAGAPIACAPQAAAegXATQgWASgjAAIgUgBIgRgDIgFAGIgCAHQAAAJAIAEQAJAEASAAIAbgCIAdgCQAZAAAOAKQANALAAATQAAAdgcAUQgdATgrAAQgjAAgXgOgAgdhaQgKAMAAASQAAATAJALQAKALAOAAQAPAAAKgLQAKgMAAgSQAAgTgJgLQgKgMgPAAQgPAAgJAMg");
	this.shape.setTransform(102.7,8.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhZBbQgJgDAAgJQAAgFAJgEIAEgCQAFgDACgFQACgGAAgOIAAgNIAAgOIAAgSQAAgdgCgJQgBgJgEgCIgJgDQgLgDAAgHQAAgEAEgDQADgDAIgEIAagIIATgDQAGAAACACQACAEAAAFIAAANIAAACIACAAIABAAIAAgBIAFgEIADgDQAUgTAWAAQAOAAAMAGQAMAGAJAJQAIALADANQAEAOAAAeIAAAYIAAAMIAAAKQAAANACAFQABAFAFADIAFACQAJAEAAAFQAAAJgJACQgIAEgcAAQgagBgJgCQgIgDAAgHQAAgHAJgEIAHgCQAEgDACgHQABgJAAgTQAAg6gHgOQgIgQgTABQgJgBgJAHQgJAFgEAKQgEAIgCAPQgCANAAAkQAAASACAGQABAFAEADIAHACQAJAEAAAHQAAAHgJADQgIADgYAAQgcAAgJgDg");
	this.shape_1.setTransform(81.4,5.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgfCDQgKgDABgJQgBgGAKgDIAEgCQAFgDABgGQACgGAAgOIAAgMIAAgPIAAgTQAAgdgBgHQgCgJgDgCIgJgDQgLgEAAgGQAAgEAEgDQADgEAIgDIAbgJIATgDQAFAAACADQACAEAAAIIAAALIAAAJIgCAtIAAABIAAAtQAAASABAHQACAHAEACIAHADQAJAEAAAHQAAAHgJADQgJADgYAAQgaAAgJgDgAgWhcQgIgGAAgKQAAgKAJgHQAJgIAMAAQALAAAIAHQAIAHgBAKQAAAKgHAHQgJAHgMAAQgMAAgIgHg");
	this.shape_2.setTransform(65.3,1.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgTBNQgLgSgZg8IgLgcQgNgigIgEIgFgCQgLgFAAgHQAAgHAJgDQAJgCAeAAQAZAAAJACQAJADAAAHIgBAGIgEADIgGAEQgHACAAAEIAEAPIAOAjIAPAjQAEAJACAAQACAAAEgGIAIgPIAUguQAGgRAAgHIgBgHIgEgDIgFgDQgJgDAAgGQAAgHAJgDQAIgCAWAAQAUAAAHACQAIADAAAHQAAAHgJADIgHADQgIAEgQAkIgFALIgHARQgqBegLABQgIgBgKgRg");
	this.shape_3.setTransform(50.7,5.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AggCDQgIgDgBgJQABgGAIgDIAFgCQAFgDABgGQADgGAAgOIAAgMIAAgPIAAgTQAAgdgCgHQgBgJgEgCIgJgDQgLgEAAgGQAAgEADgDQAEgEAIgDIAbgJIATgDQAFAAACADQADAEAAAIIAAALIgBAJIgCAtIAAABIAAAtQAAASACAHQABAHAEACIAHADQAJAEAAAHQAAAHgJADQgIADgZAAQgaAAgKgDgAgWhcQgHgGgBgKQAAgKAJgHQAJgIAMAAQALAAAIAHQAIAHAAAKQgBAKgHAHQgKAHgLAAQgMAAgIgHg");
	this.shape_4.setTransform(35.9,1.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhDB4QgXgPAAgUQAAgJAEgGQAFgGAKAAQAIAAAEAEQAFAFACAIQAEAOAMAHQALAIAXAAQAXAAAQgJQARgKAAgOQAAgIgGgFQgHgFgLAAIgVACIgcABQggAAgSgLQgRgLAAgPQAAgJAGgJQAGgIAOgIQgLgJgFgMQgGgLAAgPQAAgdAXgUQAWgUAjAAIASACIAcAFQAHAAAIgDQAIgEALgIIAGAGIACAGQAAAIgGAHQgFAHgLAGIAGAPIACAPQAAAegXATQgWASgjAAIgUgBIgRgDIgFAGIgCAHQAAAJAIAEQAJAEASAAIAbgCIAdgCQAZAAAOAKQANALAAATQAAAdgcAUQgdATgrAAQgjAAgXgOgAgdhaQgKAMAAASQAAATAJALQAKALAOAAQAPAAAKgLQAKgMAAgSQAAgTgJgLQgKgMgPAAQgPAAgJAMg");
	this.shape_5.setTransform(21.8,8.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgNBfIgUgDIgFADIgGABIgEgBIgDgCQgGgFgGgPQgFgPAAgOQAAgFADgEQADgEAFAAQAIAAAJAPIAHALQAFAHAKAEQAJAFAKAAQANgBAHgFQAHgHAAgKQAAgQgegOIgLgGQgcgOgKgLQgKgLAAgSQAAgXAQgPQARgQAaAAIAMABIANACIAJgDIAGgBQAJAAAIAOQAJAPAAAQQAAAGgDAEQgDADgFAAQgFAAgEgDQgEgEgFgIQgHgMgHgEQgIgFgKAAQgKAAgGAGQgHAGAAAKQAAAIAHAGQAHAHAWALIACABQAzAYAAAfQAAAZgUARQgTARgeAAg");
	this.shape_6.setTransform(3.5,5.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AA8CFIgIgBQgIgDgRgWIgIgKIgDgEQgsg6gEAAQAAAAgBABQAAAAAAAAQgBAAAAABQAAAAgBABIAAAHIAAAIIABAnQABAKADAEIAKAFQAIADAAAIQAAAGgJADQgJADgYAAQgcAAgJgDQgIgCAAgJQAAgGAIgDIAFgCQAFgDACgJQACgJAAgVIAAgXIAAgcIAAgWIgBhEQgBgRgDgDQgCgCgJgDIgGgCIgGgDIgCgFQAAgEAEgEQADgDANgEIAZgHIATgDQAFAAACAEQADADAAAJIgBAjIgBAvIAAAuIABAJQAAAAAAABQAAAAABAAQAAABAAAAQABAAAAAAIAIgFIANgKIASgSQAEgFAAgDQAAgBgHgDQgGgEAAgGQAAgIAJgEQAKgCAaAAQARAAAIACQAIAEAAAHQAAAJgNADQgOADgFADQgGAEgQAQIgDACIgGAIIgCADQAAADAQAWIACACIAfAmQANAPAHAGQAFACAMAEQALAEAAAIQAAAHgIAEQgJAEgTgBg");
	this.shape_7.setTransform(-13.9,1.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AhZBbQgJgDAAgJQAAgFAJgEIAEgCQAFgDACgFQACgGAAgOIAAgNIAAgOIAAgSQAAgdgCgJQgBgJgEgCIgJgDQgLgDAAgHQAAgEAEgDQADgDAIgEIAagIIATgDQAGAAACACQACAEAAAFIAAANIAAACIACAAIABAAIAAgBIAFgEIADgDQAUgTAWAAQAOAAAMAGQAMAGAJAJQAIALADANQAEAOAAAeIAAAYIAAAMIAAAKQAAANACAFQABAFAFADIAFACQAJAEAAAFQAAAJgJACQgIAEgcAAQgagBgJgCQgIgDAAgHQAAgHAJgEIAHgCQAEgDACgHQABgJAAgTQAAg6gHgOQgIgQgTABQgJgBgJAHQgJAFgEAKQgEAIgCAPQgCANAAAkQAAASACAGQABAFAEADIAHACQAJAEAAAHQAAAHgJADQgIADgYAAQgcAAgJgDg");
	this.shape_8.setTransform(-35.7,5.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAgBWIgJgJIgIAEQgWAPgXAAQgbAAgQgQQgQgPAAgaQAAgdAVgPQAVgRAnAAQAIAAAFADQAFADAAAHQAAAKgNAAQgSAAgLAIQgLAJAAAQQAAAOAKAJQAJAJARAAQAQAAAIgIQAIgIgBgTIAAhFQAAgQgGgJQgIgJgMAAQgIAAgIAFQgIADgHAJIgEAEQgLAOgMAAQgIAAgEgEQgEgFgBgIQAAgRAWgMQAVgMAhAAQAUAAAOAGQAPAFAJAKQAEAHADAMQACALAAAaIAAA6QABALABAFQACAFAEABIAFABQAMAEAAAGQAAAIgNAIQgMAHgQAAQgIAAgKgKg");
	this.shape_9.setTransform(-56.1,5.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAaCDQgKgDABgGQgBgIAKgDIAHgDQADgDACgHQACgIAAgUQAAg6gHgOQgHgPgUAAQgJAAgIAGQgKAGgFAJQgDAHgCAOQgCAOAAAlQAAASACAGQACAGADACIAHADQAKADAAAIQAAAGgJADQgJADgYAAQgdAAgJgDQgJgCAAgJQAAgGAJgDIAGgCQAEgDACgIQACgHAAgVIAAgdIAAgcIgBhSQgBgVgDgDQgCgDgKgDQgMgDAAgHQAAgEAFgEQAFgDAPgHIATgEIARgDQAGAAACAEQADAEAAAIIAAAHIgCBJIAAAJIABAFIADABIAEgEIAHgHQAIgJALgFQAKgEAKgBQAgABAQAUQAPAVAAAoIAAARIAAAgIAAALQAAAJACAFQACAEAEACIAFACQAIADABAGQAAAJgJACQgJADgdAAQgXAAgJgDg");
	this.shape_10.setTransform(-77.3,1.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgmCCQgKgDAAgIQAAgHAKgEQAKgEABgCQACgEACgeIABhWIgBgwIgCgdQAAgGgDgBQgDgCgIABIgIAAQgMAAgHACQgHADgGAHIgFANIgGAMIgFAGQgDACgEAAQgFAAgCgFQgDgEAAgMQAAgYAGgPQAFgOAJAAIACAAQAPACAWAAIBrAAQAWAAAPgCIACAAQAJAAAFAOQAGAPAAAYQAAAMgDAEQgCAFgGAAIgGgCIgGgGIgFgMIgGgNQgFgHgHgDQgHgCgNAAIgHAAQgIgBgDACQgDABgBAGIgBAdIgBAwIABBWQABAeACAEQACACAKAEQAKAEAAAHQAAAIgKADQgLAEgcgBQgcABgKgEg");
	this.shape_11.setTransform(-99.8,1.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.thanksgiving, new cjs.Rectangle(-113.7,-22.5,227.5,47.5), null);


(lib.TASTINGEVENTNEARYOU = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgSA3QgKgDgGgHQgHgGgEgJIgDgJIgBgLIAAgeIAAgfQAAgBAAAAQAAgBABAAQAAgBAAAAQAAAAABgBIADgBIAFgBIADAAIAFABQABABAAAAQABABAAAAQAAAAABABQAAABAAAAIAAA6QAAAGACAGQACAGADAFQAEAFAGACQAFADAGAAQAHAAAGgDQAFgCAEgFQAEgEACgGQABgHAAgGIAAg5QAAgEADgBIAFgBIAEgBIAEABIAEACQAAAAAAAAQABABAAAAQAAABAAAAQAAABAAABIAAA9IgBALIgDAJQgEAJgHAGQgGAHgJADQgJAEgLAAQgJAAgJgEg");
	this.shape.setTransform(103.8,-0.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgLA5IgMgDIgKgFIgJgHQgIgIgFgLIgEgLIgBgMIABgLIAEgLQAFgLAIgIIAJgHIAKgGIAMgDIALgBIAMABIAMADQALAFAIAIQAIAIAFALQAFALAAALIgCAMIgDALQgFALgIAIQgIAIgLAEIgMADQgGACgGAAQgFAAgGgCgAgOgjQgHADgFAFQgGAGgDAGQgDAIAAAHQAAAIADAIQADAGAGAFQAFAGAHADQAHADAHAAQAHAAAHgDQAHgDAGgGQAFgFADgGQAEgIAAgIQAAgHgEgIQgDgGgFgGQgGgFgHgDQgHgDgHAAQgHAAgHADg");
	this.shape_1.setTransform(90.9,-0.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgEA7IgDgBIgBgBIgBgCIAAgoIgBgHIgEgGIgggxIAAgBQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBIADgDIAEgCIAEAAIADAAIADADIAWAkIADACIACABIACgBIADgCIAXgkIACgDIAEgBIAEABIAEABIAEADIABADIAAACIgBABIggAyIgDAGIgBADIAAACIAAAoQgCAEgDABIgGAAg");
	this.shape_2.setTransform(79.1,-0.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAcA6IgCgCIgDgBIgBgBIgUgdIgCgFIgFgBIgOAAQgBAAAAABQgBAAAAAAQgBAAAAAAQgBABgBAAQAAAAAAABQAAAAgBABQAAAAAAABQAAAAAAABIAAAcQAAABAAAAQAAAAAAABQgBAAAAAAQAAABAAAAIgFABIgEABIgEAAQgDAAgCgCQgCgBAAgEIABhnQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAAAIADgBIAwAAQAIgBAHADQAIADAGAFQAFAFADAHQADAHAAAJQAAAJgDAHQgFAEgDAEIgIAGQgEACAAADIAAACIAEAHIAHAJIAGAJIADAGQAAAAgBAAQAAABAAAAQAAABAAAAQgBABAAAAIgEACIgDACIgFABgAgXgkQAAABgBAAQAAABgBAAQAAABAAAAQAAABAAABIAAAZQAAABAAABQAAABAAAAQABABAAAAQABABAAAAQADABADAAIAWAAIAIgBQAEgBADgCQADgCACgEQACgDAAgFQgBgKgGgEQgDgCgEgCQgDgBgFAAIgWAAQgDAAgDABg");
	this.shape_3.setTransform(63.8,-0.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAsA5IgCAAIgHAAQgDgBgBgDIgGgPIgCgDIgEgBIglAAIgBABIgCABIgCABIgBABIgGAPIgCACIgDABIgDABIgDAAIgEAAIgDAAIgDgCQAAAAgBAAQAAAAAAgBQAAAAAAAAQgBAAAAgBIAvhqQAAAAABgBQAAAAAAAAQABgBAAAAQAAAAABAAIADgBIAFAAQAAAAABABQABAAAAAAQABABAAAAQAAABAAAAIAtBqIAAABQAAAAAAAAQAAABAAAAQAAAAAAABQgBAAAAAAIgDABgAgBgRIgBACIgBADIgCAFIgDAHIgDAFIgBAFIgBACIABADIACABIAWAAIACgBIABgCIgCgFIgEgJIgDgJIgDgGIgDgBg");
	this.shape_4.setTransform(52,-0.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgmA4IgDgBQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAAAIAAhpQAAAAAAAAQAAgBAAAAQAAAAABgBQAAAAAAAAIAEgBIBOAAIADABIABAEIABAEIAAADIgBAFIgEACIg6AAIgDACIgCAEIAAAPQAAABABAAQAAABAAAAQAAABAAAAQABAAAAABQAAAAABAAQAAAAABABQAAAAABAAQAAAAABAAIAlAAQAAAAABAAQAAAAABAAQAAABAAAAQAAAAAAAAIACAEIAAAFIAAACQAAAFgEABIgkAAQgBAAAAABQgBAAgBAAQAAAAgBABQAAAAgBAAQAAABAAAAQgBABAAABQAAAAAAABQgBAAAAABIAAARQAAAAABABQAAAAAAABQAAAAAAABQABAAAAAAQAAABABAAQAAAAABABQAAAAABAAQAAAAABAAIA5AAQAEACAAAFIAAADIAAAFIgCADQAAAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAg");
	this.shape_5.setTransform(41.6,-0.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAhA7QgCgBgCgDIgug/QAAAAgBgBQAAAAAAAAQgBAAAAAAQgBAAAAAAIgDABQgBAAAAABQAAAAAAAAQgBABAAAAQAAABAAAAIAAA6QgBACgDABIgFABIgHAAQgDgBgCgDIAAhrQAAAAAAgBQAAAAABAAQAAgBAAAAQAAAAABAAIADgCIAEgBIADAAQAFAAADAEIAuA9IADABIACAAIABgCIAAg6QAAAAABgBQAAAAAAgBQAAAAABAAQAAAAABAAIADgCIAEAAIAEAAQAFAAACAEIAABsQAAABgBAAQAAABAAAAQgBABAAAAQgBAAAAABQgBAAAAAAQgBAAAAABQgBAAgBAAQAAAAgBAAg");
	this.shape_6.setTransform(29.5,-0.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgBA5IgGgBQgCgBAAgDIAAhTQAAgBAAgBQAAAAgBgBQAAAAAAgBQAAAAgBgBQgBgBgEAAIgJAAIgJAAIgEAAQgDAAgCgCIgBgGIAAgDIABgEIABgDIAEgBIBNAAQAEAAABACIABAGIAAACIgBAFIgCADQAAAAAAABQgBAAAAAAQAAAAgBAAQAAAAgBAAIgWAAIgFABQAAABgBAAQAAABAAAAQAAABgBABQAAAAAAABIAABSIgBAEIgDABIgEABg");
	this.shape_7.setTransform(14.1,-0.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAhA7QgCgBgCgDIgug/QAAAAgBgBQAAAAAAAAQgBAAAAAAQgBAAAAAAIgDABQgBAAAAABQAAAAAAAAQgBABAAAAQAAABAAAAIAAA6QgBACgDABIgFABIgHAAQgDgBgCgDIAAhrQAAAAAAgBQAAAAABAAQAAgBAAAAQAAAAABAAIADgCIAEgBIADAAQAFAAADAEIAuA9IADABIACAAIABgCIAAg6QAAAAABgBQAAAAAAgBQAAAAABAAQAAAAABAAIADgCIAEAAIAEAAQAFAAACAEIAABsQgBABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQgBAAAAAAQgBAAAAABQgBAAgBAAQAAAAgBAAg");
	this.shape_8.setTransform(3.4,-0.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AglA4IgEgBQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAAAIAAhpQAAAAABAAQAAgBAAAAQAAAAABgBQAAAAAAAAIAEgBIBPAAIACABIABAEIAAAEIAAADIgBAFIgCACIg7AAIgDACIgBAEIAAAPQAAABAAAAQAAABAAAAQAAABAAAAQABAAAAABQAAAAABAAQAAAAABABQAAAAABAAQAAAAABAAIAlAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAABAAIABAEIAAAFIAAACQAAAFgEABIglAAQAAAAgBABQAAAAgBAAQAAAAAAABQgBAAAAAAQgBABAAAAQgBABAAABQAAAAAAABQAAAAAAABIAAARQAAAAAAABQAAAAAAABQAAAAAAABQABAAAAAAQAAABABAAQAAAAABABQAAAAABAAQAAAAABAAIA6AAQADACAAAFIAAADIgBAFIAAADQgBAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAg");
	this.shape_9.setTransform(-7.5,-0.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgBA4IgEgIIgFgNIgIgQIgIgSIgIgRIgGgPIgEgMIgCgFIABgDIAEgDIAEgCIAEAAQABAAAAAAQABAAAAAAQABABAAAAQABAAABAAIACAFIAYA4IABABIABABQAAAAABAAQAAAAABgBQAAAAAAAAQABgBAAgBIAXg4IADgEQABAAAAgBQABAAAAAAQABAAAAAAQABgBABAAIADABIAFABIADADQABAAAAAAQAAABABAAQAAABAAAAQAAAAAAABIgCAFIgFALIgGAQIgIARIgIATIgIAQIgFAOIgDAGIgBACIgBABQAAAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAAAg");
	this.shape_10.setTransform(-18.5,-0.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgmA4IgDgBQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAAAIAAhpQAAAAABAAQAAgBAAAAQAAAAABgBQAAAAABAAIADgBIBPAAIACABIABAEIAAAEIAAADIgBAFIgCACIg7AAIgDACIgBAEIAAAPQAAABAAAAQAAABAAAAQAAABAAAAQABAAAAABQAAAAABAAQAAAAABABQAAAAABAAQAAAAABAAIAlAAQAAAAABAAQAAAAABAAQAAABAAAAQAAAAABAAIABAEIAAAFIAAACQAAAFgEABIglAAQAAAAgBABQAAAAgBAAQAAAAgBABQAAAAgBAAQAAABAAAAQgBABAAABQAAAAAAABQAAAAAAABIAAARQAAAAAAABQAAAAAAABQAAAAAAABQABAAAAAAQAAABABAAQAAAAABABQAAAAABAAQAAAAABAAIA6AAQADACAAAFIAAADIgBAFIgBADQAAAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAg");
	this.shape_11.setTransform(-28.4,-0.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgIA6QgGgBgGgDQgFgCgFgDIgJgHIgIgIIgFgKQgFgMAAgMQAAgFABgGQABgGADgGQAFgKAIgIIAJgHIAKgGIAMgDIALgBIANACQAGABAGACQAMAGAJAKIAAACIgBADIgEAFIgEADIgEABQgCAAgDgCIgGgFIgJgGQgFgCgIAAQgHAAgHADQgHADgGAFQgFAGgDAHQgDAHAAAHQAAAIADAHQADAHAFAFQAGAGAHADQAHADAHAAIAIgBIAIgBIAGgEQAEgCACgEIAAgCQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAAAAAgBIgEgBIgUAAQgBAAAAAAQgBAAAAAAQAAAAgBAAQAAgBAAAAIgCgDIAAgFIAAgDIABgFIADgCIAwAAIABABIACABQACAFAAAGIAAAEIgBAFQgDAJgGAGQgGAHgGAFQgIAEgIACQgIADgJAAIgLgBg");
	this.shape_12.setTransform(-46.2,-0.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAhA7QgCgBgCgDIgug/QAAAAgBgBQAAAAAAAAQgBAAAAAAQgBAAAAAAIgDABQgBAAAAABQAAAAAAAAQgBABAAAAQAAABAAAAIAAA6QgBACgDABIgFABIgHAAQgDgBgCgDIAAhrQAAAAAAgBQAAAAABAAQAAgBAAAAQAAAAABAAIADgCIAEgBIADAAQAFAAADAEIAuA9IADABIACAAIABgCIAAg6QAAAAABgBQAAAAAAgBQAAAAABAAQAAAAABAAIADgCIAEAAIAEAAQAFAAACAEIAABsQAAABgBAAQAAABgBAAQAAABAAAAQgBAAAAABQgBAAAAAAQgBAAAAABQgBAAgBAAQAAAAgBAAg");
	this.shape_13.setTransform(-58.6,-0.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgDA7QgEAAgCgEIAAhtIACgCIAFgBIACAAIAEAAQAFAAABADIAABsIgCADIgEABIgEABg");
	this.shape_14.setTransform(-67.1,-0.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgBA5IgGgBQgCgBAAgDIAAhTQAAgBAAgBQAAAAgBgBQAAAAAAgBQAAAAgBgBQgBgBgEAAIgJAAIgJAAIgEAAQgDAAgCgCIgBgGIAAgDIABgEIABgDIAEgBIBNAAQAEAAABACIABAGIAAACIgBAFIgCADQAAAAAAABQgBAAAAAAQAAAAgBAAQAAAAgBAAIgWAAIgFABQAAABgBAAQAAABAAAAQgBABAAABQAAAAAAABIAABSIgBAEIgDABIgEABg");
	this.shape_15.setTransform(-74.3,-0.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgZA2QgMgEgJgJIgBgCIAAgCIABgEIADgEIAFgDIADgBQADAAADACIAHAFIAKAFQAFACAHAAIAIgBQAFAAAEgCQAEgCADgDQADgEgBgFQAAgEgCgDQgDgDgFgBIgMgDIgNgBIgNgDIgMgEQgFgEgDgGQgDgFAAgJQAAgJAEgGQAFgHAHgEQAGgEAIgCQAJgCAGAAIALABIAMACIALAFQAFADAEADIAAACIABACIgBAEIgEAEIgFACIgDABIgEAAQgGgFgGgDQgIgDgHAAIgHAAIgIADIgGAFQgDADAAAEQAAAGAGADQAFADAJABIAQACQAKACAHADQAJADAFAFQAGAGAAAMQAAAKgFAHQgFAHgHAFQgHAEgJADQgJACgHAAQgMAAgNgFg");
	this.shape_16.setTransform(-84.4,-0.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAsA5IgCAAIgHAAQgCgBgCgDIgGgPIgCgDIgEgBIglAAIgBABIgCABIgCABIgBABIgGAPIgCACIgDABIgDABIgEAAIgDAAIgDAAIgDgCQAAAAgBAAQAAAAAAgBQAAAAAAAAQgBAAAAgBIAvhqQAAAAABgBQAAAAAAAAQABgBAAAAQAAAAABAAIADgBIAFAAQAAAAABABQABAAAAAAQABABAAAAQAAABAAAAIAtBqIAAABQAAAAAAAAQAAABAAAAQAAAAAAABQgBAAAAAAIgEABgAAAgRIgBACIgCADIgCAFIgDAHIgCAFIgCAFIgCACIACADIACABIAVAAIADgBIABgCIgCgFIgEgJIgDgJIgDgGIgDgBg");
	this.shape_17.setTransform(-95.3,-0.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgBA5IgGgBQgCgBAAgDIAAhTQAAgBAAgBQAAAAgBgBQAAAAAAgBQAAAAgBgBQgBgBgEAAIgJAAIgJAAIgEAAQgDAAgCgCIgBgGIAAgDIABgEIABgDIAEgBIBNAAQAEAAABACIABAGIAAACIgBAFIgCADQAAAAAAABQgBAAAAAAQAAAAgBAAQAAAAgBAAIgWAAIgFABQAAABgBAAQAAABAAAAQAAABgBABQAAAAAAABIAABSIgBAEIgDABIgEABg");
	this.shape_18.setTransform(-105.5,-0.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.TASTINGEVENTNEARYOU, new cjs.Rectangle(-112.2,-10.2,224.5,20.6), null);


(lib.savorysides = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgNBfIgUgEIgFAEIgGABIgEgBIgDgCQgGgFgGgPQgFgPAAgOQAAgFADgEQADgEAFAAQAIAAAJAOIAHAMQAFAHAKAEQAJAFAKgBQANAAAHgFQAHgHAAgKQAAgQgegOIgLgFQgcgOgKgMQgKgLAAgSQAAgXAQgQQARgPAaAAIAMABIANACIAJgDIAGgBQAJAAAIAOQAJAOAAARQAAAGgDAEQgDADgFAAQgFAAgEgDQgEgDgFgKQgHgLgHgEQgIgFgKAAQgKAAgGAGQgHAGAAAJQAAAJAHAGQAHAHAWALIACABQAzAYAAAeQAAAagUARQgTARgeAAg");
	this.shape.setTransform(97.6,3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag7BFQgagaAAgoQAAgqAbgcQAbgcAoAAQAkAAAUAVQAVAUAAAiQAAALgDAEQgEAEgNAAIhGAAQgGgBgDgDQgDgDAAgEQAAgFADgCQADgDAGAAIAmAAIAJgCQACgBAAgEQAAgSgMgMQgMgMgQAAQgWAAgKATQgLATAAAbQAAAcAPAVQAOAUAXABQANAAAKgDQAJgEAJgFIAGgGQAKgHAFgBQAEAAACADQADADAAADQAAAFgFAGQgEAHgIAGQgQANgPAGQgOAGgSgBQgmAAgagag");
	this.shape_1.setTransform(80.1,3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhPBvQgWgZAAgoQAAgsAZgbQAZgcAmgBIANACQAGACADAEQADAEAAAEQAAALgMgBIgFAAIgEgBQgVABgMARQgMAPAAAdQAAAfANATQANATAVABQASAAALgLQALgLAAgVIAAgyIAAhTQAAgNgDgFQgDgFgGgDIgFgBQgMgDAAgHQAAgEAFgEQAFgEAOgFIAUgFIARgDQAGABADADQACADAAAJIAAAJIgCBxIABBMQACASADACIAMAEQAKACAAAHQAAAIgbAJIgSAEIgNACQgFAAgDgDQgCgCAAgHIAAgJIAAgDIgBgCIgGAFIgJAGQgLAIgJAEQgLADgLAAQgiAAgVgYg");
	this.shape_2.setTransform(60.3,-1.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgfCDQgJgDAAgJQAAgGAJgDIAEgCQAFgDACgGQABgGAAgOIAAgMIAAgPIAAgTQABgdgCgHQgCgJgDgCIgJgDQgLgEAAgGQAAgEAEgDQADgEAIgDIAcgJIASgDQAFAAACADQADAEgBAIIAAALIAAAJIgBAtIAAABIgBAtQAAASABAHQACAHAEACIAHADQAJAEAAAHQAAAHgJADQgIADgYAAQgcAAgIgDgAgVhcQgJgGABgKQAAgKAIgHQAJgIAMAAQALAAAIAHQAHAHAAAKQABAKgJAHQgIAHgMAAQgMAAgHgHg");
	this.shape_3.setTransform(43.5,-1.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgtCEQgUgEgNgIQgHgEgFgPQgFgRAAgUQAAgJADgEQAEgFAGABQAIAAAJAQIAFAHQALAVAOAKQAOAIATABQATAAAOgMQAOgMAAgSQAAgZg2gYIgGgCQgsgTgPgQQgOgQAAgaQAAghAYgVQAYgVAngBIAVACIAZAGIAIgEIAGgCQAEAAAEADQADACAEAIQAGAKAEAMQAEAMAAAKQAAAGgDAEQgDACgFAAQgKABgJgNIgDgEQgKgOgMgGQgNgHgPAAQgUAAgLAKQgMAKAAAQQAAAPAKAKQAJAKAnAQIAIAEQAgAOAPAMQAKAJAFANQAGAMAAAPQAAAlgaAUQgbAWgtAAQgXgBgUgEg");
	this.shape_4.setTransform(27.7,-1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhUB5QgIgIAAgMQAAgIAGgHQAGgGAJAAIAIABIAGAEIAFAGQAFAIADAAQAJAAAKgOQAKgNgBgPQAAgPgMgdIgCgEIgdhAIgRgjQgEgHgKgEIAAgBQgHgCgCgDQgCgCAAgEQAAgJAJgDQALgCAaAAQAbAAAJACQAIADAAAHIAAAGIgDADIgHADQgIAEAAACIAEAPIAPAkIAPAjQAEAIADAAQABAAAEgIIANgdIANglQAFgNAAgEQAAgGgLgGQgKgFAAgFQAAgGAIgDQAJgCAUAAQAXAAAHACQAIADAAAHQAAAHgLADIgHACQgLAGgMAgIgEANIgYA7QgeBLgTAYQgTAWgbAAQgNAAgJgHg");
	this.shape_5.setTransform(-2,6.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ag3BbQgJgDAAgIQAAgGAJgEIAFgBQAEgDACgGQACgHAAgNIAAgNIAAgOIAAgMQAAgggCgLQgBgJgDgDIgJgDQgLgDAAgHQAAgEAEgDQADgEAHgDIAagIIAQgCQAIgBADAZIABADIAAABQAKgOAKgIQAKgIALAAQANAAAHAIQAIAIAAANQAAAMgGAHQgGAIgKAAIgKgCIgHgGIgFgHQgBgEgCAAQgNAAgFARQgEASAAA3QAAAPABAJQACAIAFACIAIACQALAEgBAHQABAHgLADQgKADgYAAQgcAAgJgDg");
	this.shape_6.setTransform(-17.8,2.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhCBEQgagaAAgpQAAgpAbgbQAbgbApgBQAnAAAZAaQAaAaAAAoQAAAqgbAcQgcAcgnAAQgnAAgagbgAgig1QgMAOAAAYQAAAkAQAZQAQAYAUAAQATAAAKgPQAMgPAAgZQAAgjgQgYQgPgYgVgBQgSABgLAPg");
	this.shape_7.setTransform(-35.5,3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgTBNQgLgTgZg7IgLgbQgNgjgIgEIgFgDQgLgDAAgIQAAgHAJgDQAJgCAeAAQAZAAAJACQAJADAAAHIgBAHIgEACIgGADQgHAEAAADIAEAPIAOAkIAPAjQAEAHACABQACgBAEgFIAIgQIAUgtQAGgSAAgGIgBgGIgEgFIgFgCQgJgDAAgGQAAgHAJgDQAIgCAWAAQAUAAAHACQAIADAAAHQAAAHgJADIgHADQgIAEgQAkIgFALIgHARQgqBfgLAAQgIAAgKgSg");
	this.shape_8.setTransform(-55.3,3.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAgBWIgJgJIgIAEQgWAPgXAAQgbAAgQgQQgQgPAAgaQgBgdAWgPQAVgRAnAAQAIAAAFADQAEADABAHQAAAKgNAAQgSAAgLAIQgLAJAAAQQAAAOAJAJQAKAJARAAQARAAAHgIQAIgIAAgTIAAhFQgBgQgGgJQgIgJgLAAQgJAAgIAFQgIADgHAJIgEAEQgLAOgNAAQgGAAgFgEQgEgFgBgIQABgRAVgMQAVgMAiAAQATAAAPAGQAOAFAIAKQAFAHADAMQADALgBAaIAAA6QABALABAFQACAFADABIAGABQAMAEAAAGQgBAIgLAIQgNAHgQAAQgJAAgJgKg");
	this.shape_9.setTransform(-74.4,3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgtCEQgUgEgNgIQgHgEgFgPQgFgRAAgUQAAgJADgEQAEgFAGABQAIAAAJAQIAFAHQALAVAOAKQAOAIATABQATAAAOgMQAOgMAAgSQAAgZg2gYIgGgCQgsgTgPgQQgOgQAAgaQAAghAYgVQAYgVAngBIAVACIAZAGIAIgEIAGgCQAEAAAEADQADACAEAIQAGAKAEAMQAEAMAAAKQAAAGgDAEQgDACgFAAQgKABgJgNIgDgEQgKgOgMgGQgNgHgPAAQgUAAgLAKQgMAKAAAQQAAAPAKAKQAJAKAnAQIAIAEQAgAOAPAMQAKAJAFANQAGAMAAAPQAAAlgaAUQgbAWgtAAQgXgBgUgEg");
	this.shape_10.setTransform(-95,-1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.savorysides, new cjs.Rectangle(-107.6,-24.9,215.3,47.5), null);


(lib.orangefruit = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.interstetititialorangefruite();
	this.instance.parent = this;
	this.instance.setTransform(-70,-38.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.orangefruit, new cjs.Rectangle(-70,-38.5,140,77), null);


(lib.mainbutton = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("EgQFAzRMAAAhmhMAgLAAAMAAABmhg");
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Path_10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AizEbQgWAAgIgFQgIgFAAgOQAAgKAGgGQAGgHAJAAIARAAQAKAAAEgLQADgJAAgZIAAl7QAAgZgDgIQgCgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgJQAAgOAJgGQAIgFAWAAIFSAAQAZAAAFAVIAMA7QAEAQgGAJQgFAJgMAAQgOAAgHgOIgJgSQgGgPgPgFQgMgEggAAIhQAAQghAAgJAIQgIAJAAAiIAABlQAAAZAIAFQAFAEAdAAIAnAAQAaAAAIgEQAHgDACgNIABgFQADgVAUAAQANAAAFAIQAFAJAAAWIAABHQAAAWgFAJQgFAJgNAAQgTAAgEgWIgBgGQgCgNgHgDQgIgEgbAAIgmAAQgdAAgFAEQgIAFAAAZIAABsQAAAiADALQADALAKAEQAQAGAhAAIBVgBQAvAAAPgfIAHgQQAJgQAOAAQAMAAAFAJQAFAJgDAQIgNBCQgFAVgZAAg");
	this.shape.setTransform(21.9,28.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Path_10, new cjs.Rectangle(0,0,43.9,56.7), null);


(lib.Path_9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AgNBlQgFgDAAgHIAAiTQAAgLgLABIgyAAQgLgBAAgOQAAgUAKgBICfAAQAMABAAARQAAARgLABIgyAAQgLAAAAAKIAACTQAAAHgFADQgEACgKAAQgJAAgEgCg");
	this.shape.setTransform(9.1,10.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Path_9, new cjs.Rectangle(0,0,18.2,20.5), null);


(lib.Path_8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AhMBmQgNAAAAgPIAAiuQAAgOANAAICbAAQAGAAADAEQACAEAAAJQAAASgMAAIh5AAQgIAAAAAKIAAAcQAAAIAKABIBFAAQALgBAAATQAAAQgKAAIhFAAQgFAAgDADQgDADAAAFIAAAeQAAAKAKAAIB3AAQALAAAAASQAAASgLAAg");
	this.shape.setTransform(9,10.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Path_8, new cjs.Rectangle(0,0,18,20.4), null);


(lib.Path_7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("Ah+EYQgKgJgIgYIhIjYQgCgFgEAAQgEAAgCAFIhNDYIgJAWQgDAGgFAFQgMAJgRAAQgTAAgKgJQgLgJgJgYIimm+QgKgagHgHQgHgHgUgFQgOgCgFgFQgFgFAAgKQAAgWAdAAICvAAQAcAAAAAWQAAALgHAFQgHAFgRABQgOACgGAFQgGAFAAAKQAAAKADAJIBzFGQACAFAFAAQAEAAACgGIA/i2QAIgagHgWIgehbIgHgTQgEgJgHgFQgGgEgPgEQgNgDgGgFQgFgFAAgKQAAgZAeAAICmAAQAdAAAAAWQAAAUgcADQgQACgGAFQgGAFAAALQAAALAIAZIBgEsQACAGAEgBQAEAAABgGIBek6QADgMAAgIQAAgSgdgEQgbgCAAgWQAAgMAIgGQAHgFARAAIElAAQAVAAAJAFQAIAFAAAOQAAAKgGAHQgGAHgJAAIgRAAQgLAAgFALQgCAKAAAXIAABuQAAAdAFAHQAGAGAYAAIBzAAQAXAAAHgIQADgDAAgHIABgeIAAhoQAAgbgCgGQgCgFgFgDQgEgDgFAAIgQAAQgKAAgGgHQgHgHAAgKQAAgOAJgFQAIgFAWAAICaAAQAWAAAJAFQAJAFAAAOQAAAKgHAHQgGAHgJAAIgSAAQgEAAgEADQgFAEgBAEQgDAHAAAaIAAF8QAAAaADAIQABAFAFADQAEACAEAAIASAAQAJAAAGAHQAHAHAAAKQAAAOgJAFQgIAGgXAAIiaAAQgVAAgJgGQgIgFAAgOQAAgJAGgIQAHgHAJAAIAQAAQALAAAFgKQACgHAAgbIAAh8IgBgdQAAgHgDgEQgGgHgYAAIhzAAQgYAAgGAGQgFAHAAAdIAACBQAAAXACALQAEAKAMAAIARAAQAIAAAGAIQAGAHAAAKQAAANgIAGQgIAFgVAAIiaAAQgWAAgIgGQgJgFAAgOQAAgJAGgIQAHgHAJAAIARAAQAEAAAFgCQAEgDABgFQADgHAAgbIAAl8QAAgxgjAFQgMABgHAJQgIAJgGAWIiHGzQgJAfgKALQgKALgUAAQgTAAgLgJg");
	this.shape.setTransform(63.5,28.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Path_7, new cjs.Rectangle(0,0,127,57.9), null);


(lib.Path_6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AhTEbIgTgEQgIAAgKAJQgKAHgJABQgLAAgGgHQgGgGgEgPIgVhWQgCgFAAgMQAAgKAIgJQAHgHAMAAQANAAAIAMIAMAQQAWAgAiASQAiARAkABQAogBAagUQAZgVAAgjQAAgggbgfQgZgbhAguQg/grgPgMQgSgOgTgWQggglAAg0QAAg+ArglQArglBGgBQAnABAhAHIAWAFIALACQAIAAAMgHQAJgIAJAAQASAAAGAYIAUBcQACAEAAAHQAAAKgHAFQgHAGgLAAQgMAAgKgOQgOgVgHgIQgGgGgOgLQgjgbgtAAQgcAAgSAPQgRAPAAAaQAAAXAJANQANASAaAUIApAfQAzAjAWARQAXATAUATQAWAWAMAfQAMAeAAAhQAABJgyAtQgzAthUAAQgxAAgngNg");
	this.shape.setTransform(19,29.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Path_6, new cjs.Rectangle(0,0,38.1,59.1), null);


(lib.Path_5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("ABaBkQgGgCAAgFIgOhsQgCgGgFAAQgDAAgDAEIgxA+QgEAFgFAAQgGAAgFgGIgtg8QgCgDgEAAQgFAAgBAIIgOBnQgCALgTAAQgGAAgFgDQgGgCAAgGIAViwQACgKADgDQAEgEALAAQAKAAAFAJIA4BOQAGAJADgBQAFAAAGgIIA7hQQAFgIAKAAQAHAAADADQAEACACAJIAUC0QABALgXAAQgFAAgEgDg");
	this.shape.setTransform(12.2,10.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Path_5, new cjs.Rectangle(0,0,24.3,20.6), null);


(lib.Path_4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AA6BlQgFgBgEgFIhAhFQgKgJgUAAQgFAAgEAEQgDAFAAAGIAAA7QAAAIgGACQgFACgKAAQgRAAAAgMIAAi0QAAgIAFgCQAFgDAKAAQASAAAAAMIAAA3QAAANAJAAQALAAAGgCQADgCAFgEIBJhDQAMgLANALQAMAMgKAJIhAA7QgJAHAJAKIBOBVQAIAJgGAFQgEAEgOAAQgMAAgFgCg");
	this.shape.setTransform(9.6,10.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Path_4, new cjs.Rectangle(0,0,19.1,20.7), null);


(lib.Path_3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

}).prototype = getMCSymbolPrototype(lib.Path_3, null, null);


(lib.Path_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("Ai5EbQgWAAgIgFQgJgFAAgOQAAgKAGgHQAHgHAJAAIARAAQAKAAAFgLQACgKAAgXIAAl7QAAgYgDgJQgBgFgFgEQgEgEgEAAIgRAAQgIAAgHgHQgHgHAAgJQAAgOAJgGQAJgFAVAAIFvAAQAZAAAFAVIAMA7QAEAQgFAJQgFAJgMAAQgPAAgHgOIgIgSQgGgPgPgFQgMgEggAAIhtAAQgiAAgIAIQgJAJAAAiIAABlQAAAZAIAFQAEAEAeAAIBGAAQAaAAAIgEQAHgDACgNIABgFQADgVATAAQAOAAAFAIQAFAJAAAWIAABHQAAAWgFAJQgFAJgOAAQgSAAgEgWIgBgGQgCgNgHgDQgIgDgbAAIhFAAQgdAAgFADQgIAFAAAaIAACKQAAAbACAGQADAFAFADQAFADAFAAIAUAAQAJAAAGAHQAGAHAAAKQAAAOgJAFQgIAFgYAAg");
	this.shape.setTransform(22.5,28.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Path_2, new cjs.Rectangle(0,0,45.1,56.7), null);


(lib.Path_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AipF/QhPhTAAiLQAAhZAghEQAghCA6gnQAZgTAmgSQAngUAmgNQAJgEgCgJQgCgKgNADQgVAEgZAAQgggBgYgJQgXgJgcgSQgggUgKgEQgugWg6AZQgWAJgLgLQgMgLAGgXQAXhVBDg4QBKg9BQAXQA0APAlA0QAnA2AeALQATAGAAAPQAAAOgRADQgbAFgjgQQgfgPgegbQgfgdgvgCQgrgCgcAVQgLAJADAGQAEAHALgCQAfgHAdAGQAoAHAbAgQAkAoAuAPQA4ASAugeIAZgXQAOgMALADQAQAEgCAUQgBAUgTAZQgiAsg9AeQhFAjgeAeQgwAvgTA9QgQAzAABRQAABxArBAQAqBBBKAAQBJAAArhCQAqhCAAhwQAAhfgXg4QgZg6g2gUQgbgLAFgTQAFgUAigDQA2gHA8AtQBoBMAACkQAACOhPBVQhQBUiHAAQiDAAhPhUg");
	this.shape.setTransform(33.5,46.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Path_1, new cjs.Rectangle(0,0,67.1,93.5), null);


(lib.Path = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AihEbQgWAAgIgFQgIgFAAgOQAAgKAGgGQAGgHAJAAIARAAQAEAAAEgDQAFgEABgEQADgJAAgXIAAl+QAAgYgDgKQgBgEgFgEQgEgDgEAAIgRAAQgKAAgGgGQgHgHAAgKQAAgOAJgGQAJgFAWAAICdAAQAWAAAIAFQAJAGAAAOQAAAKgGAHQgHAGgJAAIgRAAQgOAAgEALQgDAGAAAcIAAFjQAAAcACAKQACAJAIAFQAGAEALACQAMABAaAAIAvAAQAwAAAPgfIAHgQQAIgQAPAAQAMAAAFAJQAFAJgEAQIgNBCQgFAVgZAAg");
	this.shape.setTransform(20.2,28.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Path, new cjs.Rectangle(0,0,40.4,56.7), null);


(lib.CompoundPath_5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AjmEaQgWgDgGgEQgKgFAAgNQAAgKAGgHQAFgHAKAAIARAAQAKAAAEgLQADgJAAgYIAAl5QAAgZgDgIQgEgMgKAAIgRAAQgKAAgFgGQgGgIAAgJQAAgNAKgFQAGgEAWgDQBdgNBrAAQBOAAA1ASQA0ASAnAoQAmAlATA4QAUA5AABEQAABNgZA9QgZA+gwAlQgkAegxAOQgxAOhDAAQh0AAhUgNgAgvjrQgdAEgIAMQgLAMABAhIAAFjQgBAgAVAMQANAHAnACQBNAFArhAQAsg/gBhxQAAhvgqg/Qgqg+hMAAIgcACg");
	this.shape.setTransform(26.9,29.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.CompoundPath_5, new cjs.Rectangle(0,0,53.8,59), null);


(lib.CompoundPath_4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AgeAfQgNgMAAgTQAAgRANgNQANgNARAAQASAAANANQANANAAARQAAATgNAMQgNANgSAAQgRAAgNgNgAgYgYQgKAKAAAOQAAAQAKAKQAKAKAOAAQAPAAAKgKQAJgKAAgQQAAgOgJgKQgKgKgPAAQgOAAgKAKg");
	this.shape.setTransform(4.4,4.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.CompoundPath_4, new cjs.Rectangle(0,0,8.8,8.9), null);


(lib.CompoundPath_3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AAvBeIgggxQgGgJgJAAIguAAQgEAAgDADQgDADAAAEIAAAxQAAAGgKABIgPABQgNAAAAgMIABi5QAAgIAIAAIBrAAQAgAAAUATQAVATgBAfQABAYgPAPIgWATQgIAGAEAGIAiAzQAFAHgFAEQgFAEgOAAQgRAAgFgJgAg4g4IAAAuQAAAFAEAEQAEABAFAAIA+AAQAQAAALgHQAMgJAAgRQAAgPgMgKQgLgIgQAAIg+AAQgNAAAAAKg");
	this.shape.setTransform(9.5,10.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.CompoundPath_3, new cjs.Rectangle(0,0,18.9,20.6), null);


(lib.CompoundPath_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AAJAaIgNgVIgGAAIAAAVIgJAAIAAgzIATAAQARAAAAAQQABAMgNACIAOAVgAgKgCIAHAAQAMAAAAgHQAAgIgKAAIgJAAg");
	this.shape.setTransform(2,2.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.CompoundPath_2, new cjs.Rectangle(0,0,3.9,5.2), null);


(lib.CompoundPath_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("ABnDxQhFg1gYhfIgBgDQgCgKgHgBQgGABgCAKIgBACQgYBfhHA2QhHA2hoAAQh/AAhLhQQhMhQAAiGQAAiGBMhRQBLhQCAAAQBpAABHA3QBHA2AXBgQADALAFgBQAHAAADgLIAAAAQAXhgBGg1QBHg3BoAAQB/AABMBPQBNBQAACFQAACIhNBQQhMBRiBAAQhmAAhHg2gACmiqQgoA/AABuQAABsAoA9QApA+BIAAQBGAAAog/QApg/ABhrQAAhrgqhAQgqg/hGAAQhGAAgpA/gAmFiqQgpA/AABuQAABsApA9QAoA+BIAAQBGAAApg/QApg/AAhrQAAhrgqhAQgpg/hGAAQhGAAgpA/g");
	this.shape.setTransform(55.8,29.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.CompoundPath_1, new cjs.Rectangle(0,0,111.5,59), null);


(lib.CompoundPath = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("ABCBfIgNgbQgEgGgGAAIhTAAQgJAAgEAMIgMAVQgDAIgSAAQgWAAAFgMIBZi4QAFgKAKAAQALABAFAIIBYC7QACAGgJADQgGABgIAAQgPABgDgJgAgEgdIgYAyQgCADACACQABADAEAAIAwAAQABAAAAAAQABAAABgBQAAAAABAAQAAgBABAAQACgCgCgDIgYgzQgCgEgDABQgDAAgCADg");
	this.shape.setTransform(10.5,10.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.CompoundPath, new cjs.Rectangle(0,0,21,20.7), null);


(lib.findanevent = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgGAyIAAhXIggAAIAAgLIBNAAIAAALIggAAIAABXg");
	this.shape.setTransform(48.7,0.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAYAyIgzhQIAABQIgOAAIAAhiIASAAIAzBNIAAhNIAOAAIAABig");
	this.shape_1.setTransform(39.4,0.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AggAyIAAhiIA/AAIAAALIgxAAIAAAeIAuAAIAAALIguAAIAAAhIAzAAIAAANg");
	this.shape_2.setTransform(30,0.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgFAyIgnhiIAPAAIAdBQIABAAIAdhQIAPAAIgmBig");
	this.shape_3.setTransform(21.1,0.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AggAyIAAhiIA/AAIAAALIgxAAIAAAeIAuAAIAAALIguAAIAAAhIAzAAIAAANg");
	this.shape_4.setTransform(12.7,0.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAYAyIgzhQIAABQIgOAAIAAhiIASAAIAzBNIAAhNIAOAAIAABig");
	this.shape_5.setTransform(-0.7,0.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAhAyIgKgZIguAAIgKAZIgPAAIArhiIAMAAIAqBigAASANIgSguIgSAuIAkAAg");
	this.shape_6.setTransform(-11.1,0.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgrAyIAAhiIAiAAQAJAAAJACQAKADAIAGQAHAGAFAKIAEAKIABALIgBAMIgEAKIgFAJIgHAGQgIAHgKACQgLAEgHAAgAgdAlIASAAQAIAAAHgCQAIgDAFgFQAGgEADgHIACgIIABgIIgBgIIgCgIQgDgGgGgFQgFgFgIgCQgHgCgIgBIgSAAg");
	this.shape_7.setTransform(-24.6,0.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAZAyIg0hQIAABQIgOAAIAAhiIASAAIAzBNIAAhNIAOAAIAABig");
	this.shape_8.setTransform(-35.6,0.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgGAyIAAhiIANAAIAABig");
	this.shape_9.setTransform(-42.8,0.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgeAyIAAhiIA9AAIAAALIgvAAIAAAfIAsAAIAAAMIgsAAIAAAsg");
	this.shape_10.setTransform(-48.4,0.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.findanevent, new cjs.Rectangle(-54.8,-10.6,109.6,21.2), null);


(lib.deliciousdesserts = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgNBaIgSgEIgFAEIgFABIgEgBIgDgDQgGgEgFgOQgFgOAAgNQAAgGADgDQADgEAEAAQAIAAAIAOIAHAKQAFAHAJAFQAJADAJABQALgBAIgFQAGgGAAgJQAAgPgcgOIgKgFQgbgNgJgLQgKgLAAgRQAAgWAQgOQAPgPAZAAIAMABIAMADIAIgEIAFgBQAJAAAIAOQAIANAAAPQAAAGgCAEQgEADgFAAQgDAAgEgDQgEgDgGgIQgFgMgHgEQgIgDgJAAQgJgBgHAGQgFAFgBAKQAAAHAHAGQAGAHAUAKIACABQAxAXAAAcQAAAYgSARQgTAQgcAAg");
	this.shape.setTransform(137.3,4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgIBoQgJgDgGgGQgGgFgDgKQgCgJAAgaIAAhcIgQAAIgFgBIgCgFIAAgEQAAgGASgPIAHgGIAHgGQASgQAHAAIAEACQABAAAAABQABAAAAABQAAAAAAABQAAAAAAABIAAAgIAnAAQAEAAACACQABABAAAFIAAAEQAAAFgBACQgCACgEAAIgkAAIgDABIgBAEIAABVQAAAXAEAFQAEAGAKAAQAGAAAIgDIAMgDQAEAAACADQADACAAADQAAAKgPAJQgPAJgSAAQgKAAgIgDg");
	this.shape_1.setTransform(123.8,2.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag0BWQgIgDAAgHQAAgHAIgCIAFgDQAEgCACgFQACgHAAgNIAAgMIAAgNIAAgLQAAgegCgKQgBgJgEgDIgIgDQgKgDAAgGQAAgEADgDQADgDAIgDIAXgHIAQgDQAIAAADAXIAAAEIABAAQAJgOAJgHQAKgIAKAAQAMAAAHAIQAHAHAAAMQAAAMgFAHQgGAHgKAAIgIgCIgIgFIgEgGQgBgFgCAAQgMAAgFAQQgEARAAA0QAAAPABAHQACAIAFACIAHACQAKADAAAIQAAAGgJADQgKADgXgBQgaABgJgDg");
	this.shape_2.setTransform(111.4,3.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag3BBQgZgZAAglQAAgoAZgaQAagaAmAAQAhAAAUATQATATAAAgQAAALgDADQgDAEgNAAIhBAAQgGAAgDgDQgDgDAAgFQAAgEADgDQADgCAFAAIAkAAIAJgBQACgCAAgEQAAgQgLgMQgMgLgPAAQgVAAgKASQgJASAAAZQAAAaANAUQAOAUAVAAQANAAAJgDQAJgDAIgGIAGgFQAJgHAFAAQADAAADADQACACAAAEQAAAEgEAGQgEAGgIAGQgPAMgOAGQgOAFgQAAQgkAAgYgZg");
	this.shape_3.setTransform(95.3,4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgNBaIgSgEIgFAEIgGABIgDgBIgEgDQgFgEgFgOQgFgOAAgNQAAgGADgDQADgEAEAAQAIAAAIAOIAHAKQAFAHAJAFQAJADAJABQALgBAHgFQAHgGAAgJQAAgPgcgOIgKgFQgbgNgKgLQgJgLAAgRQAAgWAQgOQAPgPAaAAIALABIAMADIAIgEIAGgBQAIAAAIAOQAIANAAAPQAAAGgDAEQgCADgGAAQgEAAgDgDQgEgDgGgIQgFgMgIgEQgHgDgJAAQgJgBgHAGQgFAFAAAKQgBAHAHAGQAGAHAUAKIADABQAwAXAAAcQAAAYgSARQgTAQgcAAg");
	this.shape_4.setTransform(78.6,4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgNBaIgSgEIgFAEIgGABIgDgBIgEgDQgFgEgFgOQgFgOAAgNQAAgGADgDQADgEAEAAQAIAAAIAOIAHAKQAFAHAJAFQAJADAJABQALgBAIgFQAGgGAAgJQAAgPgcgOIgKgFQgbgNgKgLQgJgLAAgRQAAgWAQgOQAPgPAZAAIAMABIAMADIAIgEIAGgBQAIAAAIAOQAIANAAAPQAAAGgDAEQgCADgGAAQgEAAgDgDQgEgDgGgIQgGgMgGgEQgIgDgJAAQgJgBgHAGQgFAFAAAKQgBAHAHAGQAGAHAUAKIADABQAwAXAAAcQAAAYgSARQgTAQgcAAg");
	this.shape_5.setTransform(63.7,4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ag3BBQgZgZAAglQAAgoAZgaQAagaAmAAQAhAAAUATQATATAAAgQAAALgDADQgDAEgNAAIhBAAQgGAAgDgDQgDgDAAgFQAAgEADgDQADgCAFAAIAkAAIAJgBQACgCAAgEQAAgQgLgMQgMgLgPAAQgVAAgKASQgJASAAAZQAAAaANAUQAOAUAVAAQANAAAJgDQAJgDAIgGIAGgFQAJgHAFAAQADAAADADQACACAAAEQAAAEgEAGQgEAGgIAGQgPAMgOAGQgOAFgQAAQgkAAgYgZg");
	this.shape_6.setTransform(47.1,4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AglB8IgWAAIgOAAIgPAAQgVAAgGgCQgGgDgBgHQABgHAIgEQAKgDABgCQADgEABgaIABhDIgBg/QgBgbgDgDQgBgCgKgEQgIgEgBgHQAAgHAIgCQAHgEAUAAIAQABIARAAIAXgBIATAAQBAAAAkAhQAiAhAAA9QAAA8gkAfQgjAfhEAAgAglhiQgIADgCAFQgCAHgCAUIgBA1IABBBQACAbACAGQACAFALAEQALADAQAAQAnAAAUgXQAUgYAAgxQAAgzgXgaQgWgbgrAAQgOAAgHACg");
	this.shape_7.setTransform(24.6,0.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgNBaIgSgEIgFAEIgGABIgDgBIgEgDQgFgEgFgOQgFgOAAgNQAAgGADgDQADgEAEAAQAIAAAIAOIAHAKQAFAHAJAFQAJADAJABQALgBAIgFQAGgGAAgJQAAgPgcgOIgKgFQgbgNgKgLQgJgLAAgRQAAgWAQgOQAPgPAZAAIAMABIAMADIAIgEIAGgBQAIAAAIAOQAIANAAAPQAAAGgDAEQgCADgGAAQgEAAgDgDQgEgDgGgIQgGgMgGgEQgIgDgJAAQgJgBgHAGQgFAFAAAKQgBAHAHAGQAGAHAUAKIADABQAwAXAAAcQAAAYgSARQgTAQgcAAg");
	this.shape_8.setTransform(-5.6,4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAmBYQgDgDAAgGIAAgMIAAgBIgBAAQgCAAgEAEIgDADQgIAIgKAFQgKAEgMAAQgNAAgLgFQgMgFgHgJQgJgKgDgOQgDgOgBgkIAAgMIAAgMIAAgEQAAgOgBgEQgDgEgGgCIgHgCQgJgDAAgGQAAgEAEgDQADgDAMgEIAYgHIASgCQAFAAACADQACAEAAAHIgBAHIgBBBQgBAiAIAOQAHANASAAQATAAAIgRQAJgSAAgpIAAgNQAAgOgCgEQgCgEgGgCIgHgCQgKgDAAgGQAAgEAEgDQADgDANgEIAWgHIASgCQAGAAACADQACADAAAIIgBAKIgBBGIAAAeIABALQACAHAIAEIAAAAIAEABQAJADAAAGQAAAEgDADQgDACgIADIgYAIQgMADgGAAQgFAAgCgCg");
	this.shape_9.setTransform(-23.5,4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ag+BBQgZgaAAgmQAAgmAagaQAagaAmAAQAlAAAYAYQAYAYAAAmQAAAngaAbQgZAbglAAQgmAAgYgZgAgggzQgLAOAAAXQAAAiAPAXQAOAXAUAAQARAAALgOQAKgPAAgXQAAghgOgXQgPgXgUAAQgRAAgKAOg");
	this.shape_10.setTransform(-43.3,4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgeB8QgJgDABgIQgBgGAJgDIAEgCQAFgCACgGQABgGAAgNIAAgMIAAgNIAAgSQAAgcgBgHQgBgIgEgCIgIgDQgLgDAAgGQAAgEAEgDQADgDAIgDIAagIIARgEQAFAAABAEQADADAAAIIAAAKIgBAIIgBArIAAABIgBArQAAAQACAHQABAHAEACIAHACQAJAEAAAGQAAAHgJADQgIACgXAAQgZAAgJgCgAgVhWQgHgGAAgJQAAgKAIgHQAIgHAMAAQAKAAAHAGQAIAHAAAJQAAAJgIAHQgIAHgLAAQgLAAgIgGg");
	this.shape_11.setTransform(-58,0.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Ag2BBQgZgZAAglQAAgnAagbQAagaAmAAQAdAAAUAPQAUAOAAAUQAAAIgGAGQgGAFgIAAQgJAAgFgFQgGgEgGgOQgFgMgHgFQgGgFgLAAQgTAAgLAPQgLAPAAAaQAAAeAPAUQAQATAYAAQAJAAAIgCQAHgDAHgEIAHgFQAJgHAFAAQAEAAACACQACACAAADQAAAFgEAGQgDAGgGAFQgOAMgOAFQgPAGgRAAQgkAAgYgZg");
	this.shape_12.setTransform(-71.6,4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgeB8QgJgDABgIQgBgGAJgDIAEgCQAFgCACgGQACgGAAgNIgBgMIAAgNIAAgSQAAgcgBgHQgBgIgEgCIgIgDQgLgDAAgGQAAgEADgDQAEgDAIgDIAagIIARgEQAEAAACAEQACADABAIIAAAKIgBAIIgBArIAAABIgBArQAAAQABAHQACAHAEACIAHACQAIAEABAGQAAAHgJADQgIACgXAAQgZAAgJgCgAgVhWQgHgGAAgJQAAgKAIgHQAIgHAMAAQAKAAAIAGQAHAHAAAJQAAAJgIAHQgIAHgLAAQgLAAgIgGg");
	this.shape_13.setTransform(-85.5,0.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgcB8QgJgDAAgHQAAgGAHgDIAJgEQADgDABgLIABgiIAAgbIAAggIAAgNQAAgsgBgMQgCgMgEgDIgKgEQgLgDAAgGQAAgEADgDQAEgDAMgEIAXgGIARgDQAFAAACAEQADACAAAJIgBANQgCA+AAA9IABA8QABAMADAEIAKAEQAIADAAAHQAAAGgJADQgIADgXAAQgZAAgIgDg");
	this.shape_14.setTransform(-95.5,0);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("Ag3BBQgZgZAAglQAAgoAZgaQAagaAmAAQAhAAAUATQATATAAAgQAAALgDADQgDAEgNAAIhBAAQgGAAgDgDQgDgDAAgFQAAgEADgDQADgCAFAAIAkAAIAJgBQACgCAAgEQAAgQgLgMQgMgLgPAAQgVAAgKASQgJASAAAZQAAAaANAUQAOAUAVAAQANAAAJgDQAJgDAIgGIAGgFQAJgHAFAAQADAAADADQACACAAAEQAAAEgEAGQgEAGgIAGQgPAMgOAGQgOAFgQAAQgkAAgYgZg");
	this.shape_15.setTransform(-109.2,4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AglB8IgVAAIgPAAIgPAAQgVAAgGgCQgHgDABgHQAAgHAJgEQAIgDADgCQACgEABgaIABhDIgBg/QgBgbgCgDQgDgCgIgEQgJgEAAgHQAAgHAGgCQAIgEAUAAIAPABIASAAIAXgBIAUAAQA/AAAkAhQAiAhABA9QgBA8gjAfQgkAfhFAAgAglhiQgIADgCAFQgCAHgCAUIgBA1IABBBQACAbACAGQABAFAMAEQAMADAPAAQAnAAAUgXQAUgYAAgxQAAgzgWgaQgXgbgrAAQgOAAgHACg");
	this.shape_16.setTransform(-131.7,0.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.deliciousdesserts, new cjs.Rectangle(-146.9,-22.5,293.8,45.1), null);


(lib.date = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgKBGIgEgCIgDgDIgCgEIABgDIAIgOIAGgOIAEgOQAAgHAAgIQAAgIAAgIIgEgPIgGgNIgJgPIgBgDQAAgBAAAAQAAAAABgBQAAAAAAgBQAAAAABgBIACgDIAEgBIADgBIADAAIADABQALAQAGASQAEAIABAKQACAIAAAKQAAATgHARQgGARgKAQIgFACg");
	this.shape.setTransform(60.5,0.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgmA4IgDgBQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAAAIAAhpQAAAAABAAQAAgBAAAAQAAAAABgBQAAAAABAAIADgBIBPAAIACABIABAEIAAAEIAAADIgBAFIgCACIg7AAIgDACIgBAEIAAAPQAAABAAAAQAAABAAAAQAAABAAAAQABAAAAABQAAAAABAAQAAAAABABQAAAAABAAQAAAAABAAIAlAAQAAAAABAAQAAAAABAAQAAABAAAAQAAAAABAAIABAEIAAAFIAAACQAAAFgEABIglAAQAAAAgBABQAAAAgBAAQAAAAgBABQAAAAgBAAQAAABAAAAQgBABAAABQAAAAAAABQAAAAAAABIAAARQAAAAAAABQAAAAAAABQAAAAAAABQABAAAAAAQAAABABAAQAAAAABABQAAAAABAAQAAAAABAAIA6AAQADACAAAFIAAADIgBAFIgBADQAAAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAg");
	this.shape_1.setTransform(53.5,-0.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAmA5IgFgBQgDgBAAgEIAAgyIgBgCIgDgBQAAAAgBAAQAAAAgBABQAAAAAAAAQgBABAAAAIgSAdQgCACgDAAIgDAAIgDgDIgQgcQAAAAAAgBQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAABgBAAQAAAAAAAAIgBACIAAAyQgCAFgDABIgHAAIgDAAIgDgBIgCgCIgBgDIAAhmQABgDADgBIAHgBIAEABIADADIAbAtQACADADAAIADgBIACgCIAbgsQADgFAGAAIAFAAQAAAAABABQAAAAABAAQAAABAAAAQABABAAABIAABnIgBAEIgDACIgEAAg");
	this.shape_2.setTransform(41.1,-0.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgDA7QgEAAgCgEIAAhtIACgCIAEgBIAEAAIADAAQAFAAABADIAABsIgCADIgEABIgEABg");
	this.shape_3.setTransform(32.3,-0.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgBA5IgGgBQgCgBAAgDIAAhTQAAgBAAgBQAAAAgBgBQAAAAAAgBQAAAAgBgBQgBgBgEAAIgJAAIgJAAIgEAAQgDAAgCgCIgBgGIAAgDIABgEIABgDIAEgBIBNAAQAEAAABACIABAGIAAACIgBAFIgCADQAAAAAAABQgBAAAAAAQAAAAgBAAQAAAAgBAAIgWAAIgFABQAAABgBAAQAAABAAAAQgBABAAABQAAAAAAABIAABSIgBAEIgDABIgEABg");
	this.shape_4.setTransform(25.1,-0.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAEBGQgLgQgGgRQgHgRAAgTQAAgUAHgQQAHgSAKgQIADgBIADAAIADABIAEABIADADIABAEIgBADIgIAPIgHANIgEAPQgBAIAAAIQAAAIABAHIAEAOIAGAOIAIAOIABADIgCAEIgDADIgDACIgEACIgEgCg");
	this.shape_5.setTransform(18.3,0.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgHAPIgBgDIAAgMIAAgKIADgEIAFgBIACAAIAEABQACABACADIAAAKIgBAGIgEADIgDADIgEADIgCABIgDgBg");
	this.shape_6.setTransform(8.2,5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgXA3QgJgEgJgHIAAgDIABgEIADgEIAEgDIAEgBIAFACIAFADIAHAEQAFABAFAAQAFAAAEgCQAEgBADgDQADgDADgFQABgEAAgFQAAgFgBgEIgFgGIgHgEQgEgCgEAAQgFAAgFACIgFADIgGADIgEABIgHAAQgDgBgBgDIAFgyQAAgCACgDIAGgCIAbAAIAbABQAEAAACADIABAGQAAADgBADQgCACgDABIgkAAQgGAAgCAEQgBADgBAFQABABAAAAQAAABAAAAQAAABAAAAQABAAAAABQAAAAABAAQAAABABAAQAAAAABAAQAAAAABAAIAFgBIAHAAQAIAAAIADQAGADAFAFQAGAFACAGQADAHAAAJQABAJgEAIQgEAIgFAGQgHAFgIADQgIADgJAAQgLAAgKgDg");
	this.shape_7.setTransform(1,-0.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgNAJIgEgBIgCgCIAAgEIAAgCIAAgCIABgDIACgCIACgBIAcAAIACABIACACIACADIAAACIgBAEQAAADgDACIgCAAg");
	this.shape_8.setTransform(-6.4,-0.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAKA6QgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAgSQAAgBgBAAQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAgBgBAAQAAAAgBAAQgBgBAAAAIglAAIgFgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQgBgBAAAAIABgFIAihLIADgEIAFgBIACABIAEACIADACIABADIgCAFIgFAKIgEAMIgGANIgEALIgDAEIAAACIAAACIABACQAAABABAAQAAAAAAABQABAAAAAAQABAAABAAIADAAIAGgBIAEgBQABAAAAgBQABAAAAgBQAAAAAAgBQABgBAAAAIAAgRIABgEIADgBIAEgBIADAAIACAAIADABIADACIAAADIAAARIABADQAAABABAAQAAABAAAAQABAAABAAQAAAAABAAIAIAAQAEADAAADIABAGQAAAFgCABIgEABIgFAAQgDAAgCADIgBACIgBACIABAMQAAAEgBACQAAABAAABQgBAAAAAAQgBABAAAAQgBAAgBAAIgIACg");
	this.shape_9.setTransform(-13.6,-0.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgGAHQgEgDAAgEQAAgEAEgDQADgDADAAQAFAAADADQADADAAAEQAAAEgDADQgDAEgFAAQgDAAgDgEg");
	this.shape_10.setTransform(-25.6,4.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgBA4IgEgIIgFgNIgIgQIgHgSIgJgRIgGgPIgEgMIgCgFIABgDIAEgDIAEgCIAEAAQABAAAAAAQABAAAAAAQABABAAAAQABAAABAAIADAFIAWA4IACABIABABQAAAAABAAQAAAAABgBQAAAAAAAAQABgBAAgBIAXg4IADgEQABAAAAgBQABAAAAAAQABAAAAAAQABgBABAAIADABIAFABIAEADQAAAAAAAAQAAABABAAQAAABAAAAQAAAAAAABIgCAFIgFALIgGAQIgIARIgIATIgIAQIgFAOIgDAGIgBACIgBABQAAAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAAAg");
	this.shape_11.setTransform(-33,-0.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgLA5IgMgDIgKgFIgJgHQgIgIgFgLIgEgLIgBgMIABgLIAEgLQAFgLAIgIIAJgHIAKgGIAMgDIALgBIAMABIAMADQALAFAIAIQAIAIAFALQAFALAAALQAAAGgCAGIgDALQgFALgIAIQgIAIgLAEIgMADQgGACgGAAQgFAAgGgCgAgOgjQgHADgFAFQgGAGgDAGQgDAIAAAHQAAAIADAIQADAGAGAFQAFAGAHADQAHADAHAAQAHAAAHgDQAHgDAGgGQAFgFADgGQAEgIAAgIQAAgHgEgIQgDgGgFgGQgGgFgHgDQgHgDgHAAQgHAAgHADg");
	this.shape_12.setTransform(-44.7,-0.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAhA7QgCgBgCgDIgug/QAAAAgBgBQAAAAAAAAQgBAAAAAAQgBAAAAAAIgDABQgBAAAAABQAAAAAAAAQgBABAAAAQAAABAAAAIAAA6QgBACgDABIgFABIgHAAQgDgBgCgDIAAhrQAAAAAAgBQAAAAABAAQAAgBAAAAQAAAAABAAIADgCIAEgBIADAAQAFAAADAEIAuA9IADABIACAAIABgCIAAg6QAAAAABgBQAAAAAAgBQAAAAABAAQAAAAABAAIADgCIAEAAIAEAAQAFAAACAEIAABsQgBABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQgBAAAAAAQgBAAAAABQgBAAgBAAQAAAAgBAAg");
	this.shape_13.setTransform(-57.4,-0.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.date, new cjs.Rectangle(-65.4,-10.2,130.9,20.6), null);


(lib.ctarectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D63900").s().p("AqiCoIAAlPIVFAAIAAFPg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ctarectangle, new cjs.Rectangle(-67.5,-16.7,135,33.6), null);


(lib.blackrectangleinbox = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("EgXbgkQMAu3AAAMAAABIhMgu3AAAg");
	this.shape.setTransform(0,0,1.063,1.032);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-160.5,-240.5,321,481);


(lib.atasteofwholefoods = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgJBuQgJgDgGgGQgHgGgDgKQgCgKAAgbIAAhiIgRAAIgFgBIgCgFIAAgEQAAgGATgRIAIgGIAHgGQATgRAHAAIAFABQAAABABAAQAAABAAAAQAAABABABQAAAAAAABIAAAjIApAAQAEAAACABQACACAAAFIAAAFQAAAEgCACQgCACgEAAIgmAAIgDACIgBAEIAABaQAAAYAEAFQAEAGALABQAFAAAKgEIAMgDQAEABADACQACADAAAEQAAAKgPAJQgQAJgTAAQgLAAgJgDg");
	this.shape.setTransform(53.3,25.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag7BFQgagbAAgnQAAgqAbgbQAbgdAoAAQAkABAUAUQAVAUAAAiQAAAMgDADQgEADgNABIhGAAQgGAAgDgEQgDgDAAgEQAAgFADgCQADgDAGAAIAmAAIAJgCQACgBAAgEQAAgSgMgMQgMgMgQAAQgWAAgKATQgLATAAAbQAAAcAPAVQAOAUAXAAQANAAAKgCQAJgDAJgGIAGgGQAKgIAFAAQAEAAACAEQADACAAADQAAAFgFAHQgEAGgIAGQgQANgPAGQgOAGgSAAQgmAAgagbg");
	this.shape_1.setTransform(37.1,27.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AA8CFIgIgBQgIgDgRgWIgIgKIgDgEQgsg6gEAAQAAAAgBABQAAAAAAAAQgBAAAAABQgBAAAAABIAAAHIAAAIIABAnQABAKADAEIAKAFQAIADAAAIQAAAGgJAEQgJACgYAAQgcAAgJgCQgIgDAAgJQAAgGAIgDIAFgCQAFgDACgJQACgJAAgVIAAgXIAAgcIAAgWIgBhEQgBgRgDgDQgCgCgJgDIgGgCIgGgDIgCgFQAAgEAEgEQADgDANgEIAZgHIATgDQAFAAACAEQADADAAAJIgBAjIgBAvIAAAuIABAJQAAAAAAABQAAAAABAAQAAABAAAAQABAAAAAAIAIgFIANgKIASgRQAEgGAAgDQAAgBgHgDQgGgEAAgGQAAgIAJgEQAKgCAaAAQARAAAIACQAIAEAAAHQAAAJgNADQgOADgFADQgGAEgQAQIgDACIgGAIIgCADQAAADAQAWIACACIAfAmQANAPAHAGQAFACAMAEQALAEAAAIQAAAHgIAEQgJAEgTgBg");
	this.shape_2.setTransform(17.8,22.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag3BbQgJgDAAgJQAAgGAJgDIAFgBQAEgEACgGQACgFAAgOIAAgNIAAgOIAAgLQAAgigCgJQgBgLgEgCIgIgDQgLgDAAgHQAAgEAEgDQACgDAJgEIAZgIIAPgDQAKABADAYIAAADIAAABQAKgOAKgIQAKgIALAAQANAAAHAIQAIAIAAAMQAAANgGAHQgGAIgKgBIgKgBIgHgGIgEgGQgCgGgDAAQgMABgFARQgEASAAA2QAAAQABAJQADAHAFADIAHACQAKADABAIQAAAHgKADQgLADgYAAQgcAAgJgDg");
	this.shape_3.setTransform(0.4,26.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAhBWIgKgJIgIAEQgWAPgWAAQgbAAgRgQQgRgPAAgaQAAgdAWgPQAVgRAmAAQAJAAAFADQAEADAAAHQAAAKgMAAQgSAAgLAIQgLAJAAAQQAAAOAJAJQAKAJAQAAQARAAAIgIQAIgIAAgTIAAhFQAAgQgIgJQgHgJgLAAQgKAAgHAFQgIADgHAJIgEAEQgLAOgNAAQgGAAgFgEQgFgFAAgIQABgRAVgMQAVgMAiAAQATAAAPAGQAOAFAIAKQAFAHADAMQACALAAAaIAAA6QAAALACAFQACAFADABIAGABQALAEAAAGQABAIgMAIQgNAHgQAAQgJAAgIgKg");
	this.shape_4.setTransform(-16.6,27.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("ABFCBQgLgDAAgIQAAgIAMgEIAIgEQADgDABgIQACgIAAgYIAAgKIgBhNIAAguIgXA8Qg2CMgMAAQgFAAgLgTQgKgTgag8IgohcIgCBIIAAAxIABAiQABAJADACIAIAEQALAEAAAIQAAAHgJAEQgKADgWAAQgUAAgJgEQgJgDAAgIQAAgGAKgFQAKgFABgDQACgJADgvQADguAAg6IAAgGQAAgTgCgHQgBgGgFgDIgIgEQgMgEAAgIQAAgHAIgCQAJgDAaAAIAaAAIAIACQADACANAhIAKAaIAGANQAsBtADAAQAEAAAQgnQARgmAWhBIAEgLQAHgUAFgGQADgEAHgBIAZgBQAZAAAIADQAIACAAAHQAAAIgKAEIgFACQgGADgBAHQgCAHAAAdIACBnQABAvACAHQABAEAIADIAEACIAHAEQACADAAAEQAAAIgKADQgKADgeAAQgcAAgJgDg");
	this.shape_5.setTransform(-43.2,23.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgNBfIgUgDIgFADIgGABIgEgBIgDgCQgGgFgGgPQgFgPAAgOQAAgFADgEQADgEAFAAQAIAAAJAOIAHAMQAFAHAKAEQAJAFAKgBQANAAAHgFQAHgHAAgKQAAgQgegOIgLgGQgcgNgKgMQgKgLAAgSQAAgXAQgPQARgQAaAAIAMABIANACIAJgDIAGgBQAJAAAIAOQAJAOAAARQAAAGgDAEQgDADgFAAQgFAAgEgDQgEgDgFgKQgHgLgHgEQgIgFgKAAQgKAAgGAGQgHAGAAAKQAAAIAHAGQAHAHAWALIACABQAzAYAAAeQAAAagUARQgTARgeAAg");
	this.shape_6.setTransform(102.2,-23.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhQBvQgVgZAAgnQAAgtAZgbQAZgdAnAAIAMADQAGABADAEQADAEAAAEQAAALgMgBIgFAAIgEgBQgVABgMAQQgMAQAAAdQAAAfANATQANAUAVAAQASAAALgLQALgLAAgVIAAgxIAAhUQAAgNgDgFQgDgFgGgDIgFgBQgMgDABgHQgBgEAFgEQAEgEAOgFIAVgFIARgDQAGAAADAEQADADAAAJIAAAJIgDBxIABBMQACASADACIAMAEQAKACAAAHQAAAIgbAJIgSAEIgNACQgFAAgDgDQgDgDABgGIAAgJIAAgDIgBgBIgHADIgIAHQgLAIgJADQgLAEgLAAQgiAAgWgYg");
	this.shape_7.setTransform(84.2,-27.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AhCBFQgagbAAgpQAAgpAbgbQAbgcApAAQAnAAAaAaQAZAaAAAoQAAAqgbAcQgcAdgnAAQgnAAgagbgAgjg1QgKAOgBAYQAAAkAQAYQAQAZAUAAQATAAAKgPQAMgQAAgYQAAgjgPgYQgQgYgVgBQgSABgMAPg");
	this.shape_8.setTransform(62.5,-23.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AhCBFQgagbAAgpQAAgpAcgbQAbgcAoAAQAoAAAZAaQAZAaAAAoQAAAqgbAcQgbAdgnAAQgoAAgagbgAgjg1QgLAOABAYQAAAkAPAYQAPAZAWAAQARAAAMgPQALgQAAgYQAAgjgPgYQgRgYgUgBQgSABgMAPg");
	this.shape_9.setTransform(41.9,-23.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AhcCDQgKgDAAgJQAAgHAJgDQAKgEACgDQACgEACgbIABhHIgBhDQgCgcgCgEQgCgCgKgEQgJgEAAgIQAAgHAIgDQAIgCAgAAIBvAAIASgCIAKgCIAFABIADADQAEAHADAMQADANAAAJQAAAIgDAEQgDAFgFAAQgHAAgHgNIgGgIQgEgGgIgDQgIgDgMAAIgZAAQgRAAgJACQgJACgEAEQgCAEgCAMIgBAjIAAAPQAAAJABACQACACAFAAIAdAAQAPAAAGgEQAFgEACgMIAAgDQADgTAKAAQAIAAADAKQADAJAAAkQAAAigDAKQgDAJgIAAQgKAAgDgTIAAgDQgCgLgFgFQgGgEgPAAIgdAAQgFAAgCADQgBADAAAMIAAAOIABA0QABAKADADIAJAEQALAEAAAIQAAAIgKADQgLADgcAAQgeAAgJgDg");
	this.shape_10.setTransform(20.8,-27.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("Ag7BFQgagaAAgoQAAgqAbgcQAbgcAoAAQAkABAUAUQAVAUAAAiQAAAMgDADQgEAEgNAAIhGAAQgGAAgDgEQgDgDAAgEQAAgFADgCQADgDAGAAIAmAAIAJgCQACgBAAgEQAAgSgMgMQgMgMgQAAQgWAAgKATQgLATAAAbQAAAcAPAVQAOAUAXAAQANAAAKgCQAJgEAJgFIAGgGQAKgIAFAAQAEAAACAEQADACAAADQAAAFgFAGQgEAHgIAGQgQANgPAGQgOAGgSAAQgmAAgagbg");
	this.shape_11.setTransform(-10.2,-23.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgeCEQgJgDAAgJQAAgGAIgDIAJgFQADgDABgLIACgkIAAgdIgBgiIAAgNQAAgvgBgNQgCgNgEgCIgLgFQgMgDAAgGQAAgFAEgDQAEgDANgEIAYgHIASgDQAGAAACAEQACADAAAJIAAAOQgCBBAABBIABA/QABANADAEIAKAFQAJADAAAIQAAAGgJAEQgJACgYAAQgbAAgJgCg");
	this.shape_12.setTransform(-25.3,-27.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AhCBFQgagbAAgpQAAgpAbgbQAbgcApAAQAnAAAZAaQAaAaAAAoQAAAqgbAcQgcAdgnAAQgnAAgagbgAgig1QgMAOAAAYQABAkAPAYQAQAZAUAAQATAAALgPQALgQAAgYQAAgjgQgYQgPgYgVgBQgSABgLAPg");
	this.shape_13.setTransform(-40.4,-23.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAaCEQgJgEAAgGQAAgIAJgDIAGgDQAFgDABgHQACgIAAgUQAAg6gIgOQgHgPgTAAQgJAAgJAGQgIAGgFAJQgFAHgBAOQgBAOgBAlQABASABAGQABAGAFACIAGADQAKADAAAIQgBAGgIAEQgKACgXAAQgdAAgIgCQgKgDABgJQgBgGAKgDIAEgCQAFgDACgIQACgHAAgVIAAgdIAAgcIgBhTQgBgTgDgEQgCgDgLgDQgKgDgBgHQABgEAEgEQAEgEARgGIASgEIARgDQAGAAADAEQACADAAAJIAAAIIgBBIIAAAJIAAAFIADABIAEgEIAGgHQAJgJALgEQAJgFALgBQAgABAPAUQAQAVAAAoIAAARIAAAgIAAALQABAJABAFQACAEAEACIAEACQAJADAAAGQABAJgJADQgJACgdAAQgYAAgIgCg");
	this.shape_14.setTransform(-61.9,-27.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAZBAIgnhlQgMghgHgQQgHgPgHgFIgKgEQgJgEAAgHQAAgHAIgDQAJgDAiAAQAiAAAIADQAJADAAAHQAAAIgOAFIgBAAQgFACgCACQgCADAAAEQAAAHAJAZIAeBPIANAdQAEAIADAAQADAAADgGIAMgbIADgHQAmhbAAgLQAAgGgCgEQgDgEgGgCIgEgCQgLgFAAgHQAAgHAHgDQAIgDAeAAQAcAAAIADQAIADAAAHQAAAHgLAFIgIAEQgNAIgYA/IgPAlIgjBWIgGAQQgMAegIAAQgJAAgbhHgAhLB3IgDgFQgXgzgkheIgQgsIgLgWQgFgHgGgDIgFgCQgMgEAAgIQAAgHAJgDQAIgDAjAAQAjAAAIADQAJADAAAHQAAAIgPAFIgBAAQgEACgCADQgDACAAAEQAAAGAIAWIAfBQIAOAiQAEAGADAAQADAAAEgJIAJgVQAEgMAKAAQALAAAAAMIgCAMIgYA6IgFAOQgMAegHAAQgHAAgGgQg");
	this.shape_15.setTransform(-91.4,-27.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.atasteofwholefoods, new cjs.Rectangle(-112.3,-51.4,224.6,98), null);


(lib.atasteofturkey = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.interstitialturkey();
	this.instance.parent = this;
	this.instance.setTransform(-108.5,-110);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.atasteofturkey, new cjs.Rectangle(-108.5,-110,217,220), null);


(lib.atasteoftable = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.interstitialatasteoftable();
	this.instance.parent = this;
	this.instance.setTransform(-160,-240);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.atasteoftable, new cjs.Rectangle(-160,-240,320,480), null);


(lib.atasteofpotatoes = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.interstitialmashedpotatoes();
	this.instance.parent = this;
	this.instance.setTransform(-67.5,-109.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.atasteofpotatoes, new cjs.Rectangle(-67.5,-109.5,135,219), null);


(lib.atasteofgreens = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.interstitialgreens();
	this.instance.parent = this;
	this.instance.setTransform(-63.5,-60);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.atasteofgreens, new cjs.Rectangle(-63.5,-60,127,120), null);


(lib.atasteofcranberries = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.interstitialcranberries();
	this.instance.parent = this;
	this.instance.setTransform(-80.5,-34.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.atasteofcranberries, new cjs.Rectangle(-80.5,-34.5,161,69), null);


(lib.atasteof = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgzCDQgJgCAAgIQAAgGAJgDIAEgCQAFgCACgGQABgGAAgQIAAgRIAAhYIgUAAQgEAAgCgCQgCgCAAgFIAAgEQAAgFACgCQACgCAEAAIATAAIgBgOIgBgNQAAgcARgQQARgPAdAAQAVAAANAJQANAKAAAOQAAAJgFAEQgFAFgJAAQgFAAgFgDQgFgDgDgEIgDgHQgHgNgLAAQgHAAgDAEQgEAFAAAHIAEAUQADAQABANIAaAAQAFAAABACQACACAAAFIAAAEQAAAFgCACQgCACgEAAIgaAAIAABdQAAAYABAHQACAHADACIAIADQAKADAAAIQAAAHgJADQgJACgZAAQgbAAgJgDg");
	this.shape.setTransform(81,-1.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhCBEQgagaAAgpQAAgpAcgbQAbgbAogBQAoAAAZAaQAZAaAAAoQAAAqgbAcQgbAcgnAAQgoAAgagbgAgjg1QgLAOABAYQAAAkAPAZQAPAYAWAAQARAAALgPQAMgPAAgZQAAgjgPgYQgRgYgUgBQgSABgMAPg");
	this.shape_1.setTransform(64,3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag7BFQgagaAAgoQAAgqAbgcQAbgcAoAAQAkAAAUAVQAVAUAAAiQAAALgDAEQgEAEgNAAIhGAAQgGgBgDgDQgDgDAAgEQAAgFADgCQADgDAGAAIAmAAIAJgCQACgBAAgEQAAgSgMgMQgMgMgQAAQgWAAgKATQgLATAAAbQAAAcAPAVQAOAUAXABQANAAAKgDQAJgEAJgFIAGgGQAKgHAFgBQAEAAACADQADADAAADQAAAFgFAGQgEAHgIAGQgQANgPAGQgOAGgSgBQgmAAgagag");
	this.shape_2.setTransform(33.9,3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgJBuQgJgDgGgGQgHgGgDgKQgCgKAAgbIAAhhIgRAAIgFgCIgCgFIAAgEQAAgHATgQIAIgGIAHgGQATgRAHAAIAFABQAAABABAAQAAABAAAAQABABAAABQAAAAAAABIAAAiIApAAQAEAAACACQACACAAAFIAAAFQAAAEgCACQgCACgEABIgmAAIgDABIgBAEIAABaQAAAXAEAHQAEAFALAAQAFAAAKgDIAMgCQAEgBADADQACACAAAFQAAAKgPAJQgQAJgTAAQgLAAgJgDg");
	this.shape_3.setTransform(17.8,1.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgNBfIgUgEIgFAEIgGABIgEgBIgDgCQgGgFgGgPQgFgPAAgOQAAgFADgEQADgEAFAAQAIAAAJAOIAHAMQAFAHAKAEQAJAFAKgBQANAAAHgFQAHgHAAgKQAAgQgegOIgLgFQgcgOgKgMQgKgLAAgSQAAgXAQgQQARgPAaAAIAMABIANACIAJgDIAGgBQAJAAAIAOQAJAOAAARQAAAGgDAEQgDADgFAAQgFAAgEgDQgEgDgFgKQgHgLgHgEQgIgFgKAAQgKAAgGAGQgHAGAAAJQAAAJAHAGQAHAHAWALIACABQAzAYAAAeQAAAagUARQgTARgeAAg");
	this.shape_4.setTransform(3.3,3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAgBWIgJgJIgIAEQgWAPgXAAQgbAAgQgQQgQgPAAgaQgBgdAWgPQAVgRAnAAQAIAAAFADQAEADABAHQAAAKgNAAQgSAAgLAIQgLAJAAAQQAAAOAJAJQAKAJARAAQARAAAHgIQAIgIAAgTIAAhFQgBgQgGgJQgIgJgLAAQgJAAgIAFQgIADgHAJIgEAEQgLAOgNAAQgGAAgFgEQgEgFgBgIQABgRAVgMQAVgMAiAAQATAAAPAGQAOAFAIAKQAFAHADAMQADALgBAaIAAA6QABALABAFQACAFADABIAGABQAMAEAAAGQgBAIgLAIQgNAHgQAAQgJAAgJgKg");
	this.shape_5.setTransform(-14.1,3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgmCCQgKgDAAgIQAAgIAKgDQAKgEABgCQACgEACgeIABhWIgBgwIgCgdQAAgGgDgBQgDgBgIAAIgIAAQgMAAgHACQgHAEgGAGIgFAMIgGANIgFAGQgDACgEAAQgFAAgCgFQgDgEAAgMQAAgYAGgPQAFgPAJAAIACABQAPACAWAAIBrAAQAWAAAPgCIACgBQAJAAAFAPQAGAPAAAYQAAALgDAFQgCAFgGAAIgGgCIgGgGIgFgNIgGgMQgFgGgHgEQgHgCgNAAIgHAAQgIAAgDABQgDABgBAGIgBAdIgBAwIABBWQABAeACAEQACACAKAEQAKADAAAIQAAAIgKADQgLADgcAAQgcAAgKgDg");
	this.shape_6.setTransform(-36,-1.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAoCDQgLgDAAgJQAAgGANgFIADgBQAFgCACgCQACgDAAgEIgDgQIgHgTIgDgGIgCgBIgPgCIgbAAIgQAAQgPAAgBgMQAAgQAQABIAJAAIATAAIAUABIgUgyIgRgqIgFAAIgSAtIgTAvIgSAuQgEALAAAHQAAAFADAEQACAFAFACIAGACQAMAEAAAHQAAAJgJADQgKADgcAAQgbAAgKgDQgJgDAAgJQAAgGALgFIAHgDQAOgJAMgfIAEgLIAbhBIAGgRQAbhBAGgbQACgJADgCQAFgCAKgBQAGABADACQAEACAEAIIAcA8IAkBWIAJAVQAUA2ANAGIAGACQAMAEAAAHQAAAJgMADQgKADghAAQggAAgLgDg");
	this.shape_7.setTransform(-71.2,-1.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.atasteof, new cjs.Rectangle(-86.7,-24.9,173.4,47.5), null);


(lib.whitelogo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AqoZMQk7iFjyjyQjxjyiFk6QiKlFAAlkQAAljCKlFQCFk6DxjzQDzjxE6iFQFFiKFjAAQFkAAFFCKQE6CFDyDxQDyDyCFE7QCKFFAAFjQAAFkiKFFQiFE7jyDxQjxDyk7CFQlFCKlkAAQljAAlFiKgALRMiQAAAOALAAIAyAAQALAAAAALIAACTQAAAIAGACQADACAKAAQAKAAAEgCQAFgCAAgIIAAiTQAAgLAMAAIAxAAQALAAAAgSQAAgRgMAAIigAAQgKAAAAAVgADSONIBCBFQADAEAFACQAGACALAAQAOAAAEgFQAGgEgIgJIhOhWQgJgKAKgIIBAg6QAJgJgMgMQgNgMgLALIhLBEQgFAEgDABQgGADgKAAQgKAAAAgNIAAg3QAAgMgRAAQgLAAgEADQgFACgBAIIAAC1QAAAMARAAQALAAAEgCQAGgDAAgHIAAg7QAAgHADgEQAEgEAFAAQAVgBAJAKgAhvOXQAKAAAGAJIAgAxQAFAJARAAQAOAAAFgFQAFgEgFgGIgigzQgEgGAHgGQAPgKAIgJQAOgQAAgYQABgfgVgTQgUgTggAAIhsAAQgIAAAAAIIgBC6QAAAMANAAIAPgBQAKgBAAgGIAAgxQAAgEADgDQADgDAEAAgAmPOxQAGAAAEAGIAMAbQAEAIAPAAQAIAAAGgCQAJgDgDgGIhXi8QgFgIgLAAQgMAAgEAKIhZC4QgGAMAXAAQASABADgIIAMgWQAEgLAIAAgArGNjIAOBtQAAAFAFACQAFADAEAAQAYAAgBgLIgVi2QgCgIgDgCQgEgDgGAAQgLAAgEAIIg8BQQgFAIgFAAQgFABgGgJIg3hOQgFgJgLAAQgKAAgEAEQgDADgCAKIgVCxQAAAGAGACQAFADAGAAQATAAACgLIANhoQACgIAEAAQAEAAADADIAtA9QAFAGAGAAQAGAAAEgFIAxg/QADgEADAAQAFAAACAGgAGyMaIAACwQAAAOANAAICcAAQAKAAAAgRQAAgSgKgBIh6AAQgJAAAAgKIAAgeQAAgFADgDQADgCAFAAIBGAAQAKAAAAgSQAAgSgLAAIhHAAQgJAAAAgJIAAgbQAAgKAIAAIB7AAQALAAAAgSQAAgKgCgDQgCgFgHABIicAAQgNAAAAANgAT5IwQgNANAAATQAAASANAMQANAOASAAQATAAAMgOQANgMAAgSQAAgTgNgNQgMgNgTAAQgSAAgNANgAP5JKQAnALAyAAQBUAAAzgsQAygtAAhKQAAgggMgfQgMgegWgWQgUgVgWgSQgXgRgzgkIgpgdQgbgVgNgSQgJgOAAgVQAAgaARgQQASgQAeAAQAtAAAiAcQAOAKAHAHQAGAHAOAVQAKAPAMAAQALAAAHgGQAHgGAAgIQAAgIgCgEIgUhcQgFgXgTAAQgJAAgJAGQgMAIgHAAIgMgCIgWgFQghgIgoABQhFAAgrAlQgsAmABA9QAAA0AfAmQAUAVARAPQAPALA/AsQBBAuAZAbQAcAggBAfQABAjgaAUQgaAWgpAAQgkAAgigSQghgTgWgfIgNgRQgIgLgNAAQgMAAgHAIQgIAHAAAMQAAAKACAHIAWBUQAEAQAFAGQAGAHALgBQAJAAALgIQAJgIAJAAIASAFgAjHGJIABACQAYBeBFA2QBHA2BkAAQCCAABMhRQBMhQAAiJQAAiFhMhPQhNhQh+AAQhoAAhHA3QhFA1gYBgIAAAAQgCALgHABQgHAAgCgLQgYhghHg2QhHg3hoAAQiAAAhMBRQhLBQAACIQAACFBLBQQBMBQB+AAQBoAABIg2QBHg2AYhfIAAgBQACgMAIAAQAGABADALgAFnIeQgGAGAAAKQAAAOAJAEQAIAEAUADQBVANB0AAQBFABAxgOQAvgOAlgeQAwgmAZg9QAZg9AAhOQAAhFgTg4QgVg5glglQgngng1gSQg1gThOABQhrAAheAMQgUAEgIAEQgJAEAAAOQAAAJAGAHQAGAHAIAAIARAAQALAAAEALQADAJAAAYIAAF6QAAAYgDAJQgEAMgLAAIgRAAQgIAAgGAHgAyyIfQgHAIABAJQAAAOAJAFQAIAFAWABICcAAQAYgBAJgFQAJgFAAgOQAAgKgHgHQgGgGgKAAIgTAAQgFgBgFgDQgGgDgCgFQgCgGAAgbIAAiKQAAgZAIgGQAEgDAeAAIBGAAQAbAAAHAEQAIADABANIABAFQAFAWASAAQANAAAGgIQAFgKAAgWIAAhIQAAgVgFgJQgGgJgNAAQgTAAgEAVIgBAGQgBAMgIAEQgHADgaAAIhHAAQgeAAgEgDQgIgGAAgZIAAhlQAAgiAIgJQAJgIAjAAIBtAAQAfAAANAEQAPAFAFAPIAIASQAIAOAOAAQAMAAAFgIQAGgKgEgPIgMg8QgFgVgZAAIlwAAQgVAAgJAGQgJAFAAAOQAAAJAGAIQAIAGAIAAIARAAQAEAAAEAEQAFAEAAAGQAEAIAAAYIAAF8QAAAXgCAKQgGAMgJAAIgSAAQgIAAgHAGgACorXQABAJgIAEQgoANgnAUQglASgaATQg5AoggBCQgfBEAABZQgBCLBPBTQBOBUCFABQCGAABQhVQBPhVAAiOQABilhohMQg9gtg2AHQgiAEgEAUQgFATAaAKQA2AUAZA8QAXA3ABBfQAABwgrBCQgrBChJAAQhLAAgqhBQgrhAAAhxQAAhRAQgzQATg+AwgvQAegeBGgiQA+gfAhgsQATgYABgVQACgTgQgFQgLgDgOANIgZAWQguAeg4gRQgvgPgjgpQgcgfgogIQgcgGgfAHQgLACgEgGQgCgHALgJQAbgUArABQAuADAfAcQAeAbAgAPQAjARAbgGQARgDAAgOQAAgPgTgGQgegLgng1Qgmg0g0gQQhOgWhLA9QhDA3gXBVQgGAXAMALQALALAWgJQA6gZAuAWQAKAFAgAUQAcARAWAJQAYAKAhAAQAYAAAWgEIAFgBQAJAAACAIgAvClPIBIDYQAHAXALAJQALAJATAAQATABALgLQAKgLAJggICImzQAGgXAIgJQAHgIALgCQAjgFAAAxIAAF+QAAAbgCAGQgBAFgFADQgEACgFAAIgQAAQgJABgHAGQgGAIgBAJQAAAPAJAEQAJAGAVAAICbAAQAVAAAIgFQAIgGAAgNQAAgKgGgHQgGgIgJAAIgQAAQgMAAgEgKQgCgLAAgWIAAiCQgBgcAGgIQAGgGAXAAIBzAAQAYAAAHAHQACAFABAGIAAAeIAAB8QAAAbgBAGQgGAKgKAAIgRAAQgIABgHAGQgGAIAAAJQAAAPAIAEQAJAGAVAAICaAAQAWAAAJgGQAJgEAAgPQAAgKgHgHQgGgGgKgBIgRAAQgEAAgFgCQgEgDgBgFQgDgIAAgZIAAl+QAAgaADgHQABgEAEgDQAFgEAEAAIARAAQAKAAAGgGQAHgIAAgKQgBgOgIgFQgJgFgWAAIiaAAQgWAAgIAFQgJAFAAAOQAAAKAGAIQAHAGAJAAIARAAQAFAAADADQAFADADAFQABAGAAAbIAABpIAAAdQgBAHgCADQgHAJgYgBIhzAAQgXAAgGgGQgGgHABgdIAAhuQAAgXACgKQAFgLALAAIAQAAQAKAAAFgGQAHgIAAgKQgBgOgHgFQgJgFgVAAIkmAAQgRAAgIAGQgHAFgBANQAAAVAcACQAeAEAAATQAAAHgEANIheE7QgBAFgFABQgDAAgCgGIhgktQgIgZgBgKQAAgMAHgEQAFgGARgCQAcgDgBgUQABgWgdAAIimAAQgfAAAAAaQABAJAFAFQAGAFANADQAPAEAGAEQAHAFADAJIAHAUIAfBaQAHAWgIAaIg/C3QgCAGgEAAQgFAAgCgEIhzlIQgDgIAAgLQAAgKAGgFQAGgFAOgBQARgBAGgGQAIgEgBgMQABgWgcAAIivAAQgdAAAAAWQAAAKAFAFQAFAGANACQAVAEAHAHQAHAIAJAaICnG/QAJAYALAIQAKAKATgBQARABALgKQAFgEADgHIAJgVIBOjZQABgFAEAAQAFAAACAGgAOkiCQgGAHAAAJQAAAOAJAFQAHAGAWAAIFjAAQAZAAAFgVIANhDQADgPgFgKQgEgIgNAAQgOAAgIAQIgHAQQgPAfgwAAIhUABQgigBgRgFQgKgEgDgLQgDgMAAghIAAhsQAAgZAIgFQAGgEAdAAIAmAAQAbAAAIAEQAHADACANIABAFQAEAXATAAQANgBAGgIQAEgKAAgWIAAhHQAAgWgEgJQgGgIgNgBQgTABgEAUIgBAGQgCAMgHAEQgHADgbAAIgnAAQgdAAgGgDQgIgFAAgaIAAhlQAAghAIgJQAJgJAjAAIBQAAQAfABANAEQAPAFAFAPIAJASQAHAOAOAAQANAAAEgJQAGgJgEgQIgMg7QgEgWgaAAIlTAAQgVABgJAFQgJAGAAAOQAAAJAGAHQAIAHAIAAIARAAQAEAAAEAEQAFADABAGQADAIAAAZIAAF8QAAAZgDAIQgCAFgDADQgEAEgFAAIgRAAQgJAAgGAGgAHyiCQgFAHAAAJQAAAOAIAFQAIAGAVAAIE/AAQAZAAAGgVIAMhDQAEgPgFgKQgFgIgMAAQgPAAgIAQIgHAQQgPAfgvAAIgwAAQgaAAgMgCQgMgBgGgEQgIgFgCgKQgCgJAAgcIAAllQABgbACgGQAEgLAOAAIASAAQAJAAAHgGQAGgHABgKQgBgOgIgGQgJgFgXgBIidAAQgWABgJAFQgJAGAAAOQAAAKAHAHQAGAGAKAAIARAAQAEAAAFADQAEADABAFQADAKABAXIAAGAQgBAXgDAIQgBAFgEADQgFAEgEAAIgRAAQgJAAgGAGg");
	this.shape.setTransform(0,0,0.217,0.217);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgYAZQgKgKAAgPQAAgOAKgLQAKgJAOgBQAPABAKAJQAKALAAAOQAAAPgKAKQgKALgPgBQgOABgKgLgAAWAZIgPgVQANgCAAgMQAAgQgRAAIgTAAIAAAzIAJAAIAAgVIAFAAIAOAVIAKAAg");
	this.shape_1.setTransform(28.3,12.8,0.217,0.217);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgrAiQgFAAgEgDQgEgEAAgFIAAgtQAAgKANAAIA+AAQAQAAALAJQALAJAAAPQAAAQgLAJQgLAJgQAAg");
	this.shape_2.setTransform(-2.4,18.4,0.217,0.217);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgJAHIAAgNIAIAAQALAAAAAGQAAAHgNAAg");
	this.shape_3.setTransform(28.3,12.6,0.217,0.217);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhvCtQgog/AAhrQAAhuAog/QApg/BGAAQBFAAAqBAQApA+AABsQAABrgpA/QgpA/hGAAQhGAAgpg9g");
	this.shape_4.setTransform(-10.6,6.5,0.217,0.217);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgYAfQgDAAgCgCQgBgDABgDIAZgxQACgEACAAQADAAACADIAZAzQABADgCACQAAABgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAg");
	this.shape_5.setTransform(-9.6,19.1,0.217,0.217);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgtDsQgngCgNgHQgUgMgBggIAAljQAAghALgMQAIgMAdgEIAdgDQBKAAArA/QArA+AABvQgBBxgqBAQgqA8hFAAIgKgBg");
	this.shape_6.setTransform(14,6.5,0.217,0.217);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhvCtQgog/AAhrQAAhuAog/QApg/BGAAQBFAAAqBAQApA+AABsQAABrgpA/QgpA/hFAAQhHAAgpg9g");
	this.shape_7.setTransform(1.5,6.5,0.217,0.217);

	this.instance = new lib.Path();
	this.instance.parent = this;
	this.instance.setTransform(15,-8.1,0.217,0.217,0,0,0,20.3,28.4);
	this.instance.alpha = 0.789;

	this.instance_1 = new lib.Path_1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(3.2,-11.7,0.217,0.217,0,0,0,33.5,46.8);
	this.instance_1.alpha = 0.789;

	this.instance_2 = new lib.Path_2();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-21.3,6.6,0.217,0.217,0,0,0,22.6,28.4);
	this.instance_2.alpha = 0.789;

	this.instance_3 = new lib.Path_3();
	this.instance_3.parent = this;
	this.instance_3.setTransform(-12.2,36,0.217,0.217,0,0,0,0.2,0.2);
	this.instance_3.alpha = 0.789;

	this.instance_4 = new lib.CompoundPath();
	this.instance_4.parent = this;
	this.instance_4.setTransform(-9.6,19.2,0.217,0.217,0,0,0,10.6,10.4);
	this.instance_4.alpha = 0.789;

	this.instance_5 = new lib.Path_4();
	this.instance_5.parent = this;
	this.instance_5.setTransform(4.9,19.2,0.217,0.217,0,0,0,9.7,10.4);
	this.instance_5.alpha = 0.789;

	this.instance_6 = new lib.Path_5();
	this.instance_6.parent = this;
	this.instance_6.setTransform(-16.9,19.2,0.217,0.217,0,0,0,12.2,10.4);
	this.instance_6.alpha = 0.789;

	this.instance_7 = new lib.Path_6();
	this.instance_7.parent = this;
	this.instance_7.setTransform(23.9,6.6,0.217,0.217,0,0,0,19.2,29.5);
	this.instance_7.alpha = 0.789;

	this.instance_8 = new lib.CompoundPath_1();
	this.instance_8.parent = this;
	this.instance_8.setTransform(-4.5,6.6,0.217,0.217,0,0,0,55.8,29.5);
	this.instance_8.alpha = 0.789;

	this.instance_9 = new lib.CompoundPath_2();
	this.instance_9.parent = this;
	this.instance_9.setTransform(28.4,12.8,0.217,0.217,0,0,0,2.1,2.6);
	this.instance_9.alpha = 0.789;

	this.instance_10 = new lib.Path_7();
	this.instance_10.parent = this;
	this.instance_10.setTransform(-16.2,-7.9,0.217,0.217,0,0,0,63.4,29.1);
	this.instance_10.alpha = 0.789;

	this.instance_11 = new lib.CompoundPath_3();
	this.instance_11.parent = this;
	this.instance_11.setTransform(-2.4,19.2,0.217,0.217,0,0,0,9.7,10.4);
	this.instance_11.alpha = 0.789;

	this.instance_12 = new lib.Path_8();
	this.instance_12.parent = this;
	this.instance_12.setTransform(11.4,19.2,0.217,0.217,0,0,0,9,10.4);
	this.instance_12.alpha = 0.789;

	this.instance_13 = new lib.Path_9();
	this.instance_13.parent = this;
	this.instance_13.setTransform(17.6,19.2,0.217,0.217,0,0,0,9.2,10.2);
	this.instance_13.alpha = 0.789;

	this.instance_14 = new lib.CompoundPath_4();
	this.instance_14.parent = this;
	this.instance_14.setTransform(28.3,12.9,0.217,0.217,0,0,0,4.6,4.6);
	this.instance_14.alpha = 0.789;

	this.instance_15 = new lib.CompoundPath_5();
	this.instance_15.parent = this;
	this.instance_15.setTransform(13.5,6.6,0.217,0.217,0,0,0,27,29.5);
	this.instance_15.alpha = 0.789;

	this.instance_16 = new lib.Path_10();
	this.instance_16.parent = this;
	this.instance_16.setTransform(24.8,-8.1,0.217,0.217,0,0,0,21.9,28.4);
	this.instance_16.alpha = 0.789;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_16},{t:this.instance_15},{t:this.instance_14},{t:this.instance_13},{t:this.instance_12},{t:this.instance_11},{t:this.instance_10},{t:this.instance_9},{t:this.instance_8},{t:this.instance_7},{t:this.instance_6},{t:this.instance_5},{t:this.instance_4},{t:this.instance_3},{t:this.instance_2},{t:this.instance_1},{t:this.instance},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.whitelogo, new cjs.Rectangle(-37.9,-37.9,75.9,75.9), null);


// stage content:
(lib.interstitialatasteoffivefade = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_48 = function() {
		//onhover event to reveal green cta rectangle over orange rectangle
		this.btn_main.addEventListener("mouseover", fl_MouseOverHandler.bind(this));
		this.btn_main.addEventListener("mouseout", fl_MouseOutHandler.bind(this));
		
		function fl_MouseOverHandler()
		{
			this.cta_rollover.gotoAndPlay(2);
		}
		
		function fl_MouseOutHandler()
		{
		this.cta_rollover.gotoAndPlay(13);
		}
	}
	this.frame_308 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(48).call(this.frame_48).wait(260).call(this.frame_308).wait(23));

	// button
	this.btn_main = new lib.mainbutton();
	this.btn_main.parent = this;
	this.btn_main.setTransform(160.4,240.1,1.553,0.731,0,0,0,0.2,0.1);
	new cjs.ButtonHelper(this.btn_main, 0, 1, 2, false, new lib.mainbutton(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn_main).wait(331));

	// white-logo
	this.instance = new lib.whitelogo();
	this.instance.parent = this;
	this.instance.setTransform(160,37);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(9).to({scaleX:0.11,scaleY:0.11},0).to({scaleX:1.34,scaleY:1.34,alpha:1},6,cjs.Ease.get(1)).to({scaleX:1.24,scaleY:1.24},8,cjs.Ease.get(1)).wait(308));

	// black-rectangle
	this.instance_1 = new lib.blackrectangleinbox("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(160,240);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(331));

	// fade-from-white
	this.instance_2 = new lib.whiterectanglefade();
	this.instance_2.parent = this;
	this.instance_2.setTransform(172.5,253.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({alpha:0},9).wait(322));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("Axve0IAAweMApMAAAIAAQeg");
	mask.setTransform(150.1,197.2);

	// date
	this.instance_3 = new lib.date();
	this.instance_3.parent = this;
	this.instance_3.setTransform(160,288.4);
	this.instance_3.alpha = 0;

	var maskedShapeInstanceList = [this.instance_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(37).to({y:265.4},0).to({y:309.4,alpha:1},10,cjs.Ease.get(1)).to({y:297.4},6,cjs.Ease.get(1)).wait(278));

	// mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	mask_1.graphics.p("AzUQIIAAwcMAqIAAAIAAQcg");
	mask_1.setTransform(146,103.2);

	// tasting event near you
	this.instance_4 = new lib.TASTINGEVENTNEARYOU();
	this.instance_4.parent = this;
	this.instance_4.setTransform(160,111.3);
	this.instance_4.alpha = 0;

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(9).to({y:75,alpha:1},0).to({y:121.3},10,cjs.Ease.get(1)).to({y:111.3},6,cjs.Ease.get(1)).wait(306));

	// a-taste-of
	this.instance_5 = new lib.atasteof();
	this.instance_5.parent = this;
	this.instance_5.setTransform(160,151.8);
	this.instance_5.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(25).to({alpha:1},10,cjs.Ease.get(1)).wait(222).to({alpha:0},6).wait(68));

	// whole-foods-market
	this.instance_6 = new lib.atasteofwholefoods();
	this.instance_6.parent = this;
	this.instance_6.setTransform(160,228.1);
	this.instance_6.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(25).to({alpha:1},10,cjs.Ease.get(1)).wait(102).to({alpha:0},5).wait(189));

	// savory-sides
	this.instance_7 = new lib.savorysides();
	this.instance_7.parent = this;
	this.instance_7.setTransform(160,200.7);
	this.instance_7.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(137).to({alpha:1},10,cjs.Ease.get(1)).wait(30).to({alpha:0},5).wait(149));

	// delicious-desserts
	this.instance_8 = new lib.deliciousdesserts();
	this.instance_8.parent = this;
	this.instance_8.setTransform(160,198.2);
	this.instance_8.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(177).to({y:200.2},0).to({alpha:1},10,cjs.Ease.get(1)).wait(30).to({alpha:0},5).wait(109));

	// thanksgiving
	this.instance_9 = new lib.thanksgiving();
	this.instance_9.parent = this;
	this.instance_9.setTransform(160,199.2);
	this.instance_9.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(217).to({alpha:1},10,cjs.Ease.get(1)).wait(30).to({alpha:0},6).wait(68));

	// try-new-flavors
	this.instance_10 = new lib.trynewflavors();
	this.instance_10.parent = this;
	this.instance_10.setTransform(160,150.8);
	this.instance_10.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(273).to({alpha:1},10).wait(48));

	// mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	mask_2.graphics.p("EgOfAh9IAAwdMApLAAAIAAQdg");
	mask_2.setTransform(170.8,217.3);

	// find an event
	this.instance_11 = new lib.findanevent();
	this.instance_11.parent = this;
	this.instance_11.setTransform(160,274.1);
	this.instance_11.alpha = 0;

	var maskedShapeInstanceList = [this.instance_11];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(37).to({y:300.1},0).to({y:348.1,alpha:1},10,cjs.Ease.get(1)).to({y:336.1},6,cjs.Ease.get(1)).wait(278));

	// mask (mask)
	var mask_3 = new cjs.Shape();
	mask_3._off = true;
	mask_3.graphics.p("EgOfAhGIAAwdMApLAAAIAAQdg");
	mask_3.setTransform(170.8,211.8);

	// cta-rectangle
	this.instance_12 = new lib.ctarectangle();
	this.instance_12.parent = this;
	this.instance_12.setTransform(158.6,274.8);
	this.instance_12.alpha = 0;

	var maskedShapeInstanceList = [this.instance_12];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_3;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(37).to({x:160,y:300.1},0).to({y:348.1,alpha:1},10,cjs.Ease.get(1)).to({y:336.1},6,cjs.Ease.get(1)).wait(278));

	// orange-fruit
	this.instance_13 = new lib.atasteofgreens();
	this.instance_13.parent = this;
	this.instance_13.setTransform(256.5,60);
	this.instance_13.alpha = 0;

	this.instance_14 = new lib.orangefruit();
	this.instance_14.parent = this;
	this.instance_14.setTransform(70,38.5);
	this.instance_14.alpha = 0;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_14},{t:this.instance_13}]}).to({state:[{t:this.instance_14}]},53).to({state:[{t:this.instance_14}]},10).wait(268));
	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(53).to({alpha:1},10).wait(268));

	// greens
	this.instance_15 = new lib.atasteofgreens();
	this.instance_15.parent = this;
	this.instance_15.setTransform(256.5,60);
	this.instance_15.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(63).to({alpha:1},10).wait(258));

	// mashed-potatoes
	this.instance_16 = new lib.atasteofpotatoes();
	this.instance_16.parent = this;
	this.instance_16.setTransform(67.5,337.5);
	this.instance_16.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(73).to({x:35.5,y:354.5},0).to({alpha:1},10).wait(248));

	// turkey
	this.instance_17 = new lib.atasteofturkey();
	this.instance_17.parent = this;
	this.instance_17.setTransform(211.5,370);
	this.instance_17.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_17).wait(83).to({x:230.5,y:392},0).to({alpha:1},10).wait(238));

	// cranberries
	this.instance_18 = new lib.atasteofcranberries();
	this.instance_18.parent = this;
	this.instance_18.setTransform(80.5,445.5);
	this.instance_18.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_18).wait(93).to({y:454.5},0).to({alpha:1},10).wait(228));

	// table
	this.instance_19 = new lib.atasteoftable();
	this.instance_19.parent = this;
	this.instance_19.setTransform(160,240);

	this.timeline.addTween(cjs.Tween.get(this.instance_19).wait(331));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(135.1,221.1,395,545);
// library properties:
lib.properties = {
	id: '85088BD5353243C8B4895C262600CED3',
	width: 320,
	height: 480,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/index_atlas_.png", id:"index_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['85088BD5353243C8B4895C262600CED3'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;